Repository tifapp/FitnessProject, pull requests merged in 2023-08, with the labels that each got.

#139 Remove Geocoding From Dependencies System
  components/eventForm/LocationBanner.tsx
  hooks/Geocoding.ts
  hooks/Geocoding.tsx
  lib/location/Geocoding.ts
  lib/location/index.ts
  tests/events/EventForm/EventFormScreen.test.tsx
  tests/events/EventForm/LocationBanner.test.tsx
Labels: reviews (0)

#140 Refactor location search UI
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/Explore/Explore.stories.tsx
  .storybook/components/LocationSearch/LocationSearch.stories.tsx
  lib/AppColorStyle.ts
  lib/Array.ts
  lib/Haptics.ts
  lib/location/ExpoHelpers.ts
  lib/location/RecentsStorage.ts
  lib/location/Search.ts
  screens/LocationSearch/Data.ts
  screens/LocationSearch/Icon.tsx
  screens/LocationSearch/Picker.tsx
  screens/LocationSearch/SearchResultView.tsx
  screens/LocationSearch/SearchResultsList.tsx
  screens/LocationSearch/index.ts
  screens/LocationSearch/models.ts
  screens/LocationSearch/state.ts
  tests/location/LocationSearch.test.tsx
Labels: reviews (1)

#142 Logging System
  .eslintrc.json
  .gitignore
  App.tsx
  app.config.ts
  jest.config.js
  lib/Array.ts
  lib/Filesystem.ts
  lib/Logging.ts
  lib/Sentry.ts
  package-lock.json
  package.json
  tests/Logging.test.ts
  tests/helpers/Filesystem.ts
Labels: reviews (1)

#144 Added ci for storybook
  .github/workflows/storybook-build.yml
Labels: reviews (0)

#143 Adding haptics context
  .vscode/settings.json
  App.tsx
  components/formComponents/HexColorPicker.tsx
  lib/Haptics.ts
  lib/Haptics.tsx
  tests/ExpoHaptics.test.ts
  tests/Haptics.test.ts
  tests/components/HexColorPicker.test.tsx
  tests/events/EventForm/EventFormScreen.test.tsx
  tests/helpers/Haptics.ts
Labels: reviews (2)

#146 Add Mixpanel Analytics
  App.tsx
  lib/Analytics.ts
  lib/Analytics.tsx
  lib/Haptics.tsx
  lib/JSONSerializable.ts
  package-lock.json
  package.json
  tests/AmplifyAnalytics.test.ts
Labels: reviews (0)

#145 Eas Build
  .eslintrc.json
  App.tsx
  app.config.ts
  assets/fonts/OpenDyslexic3-Bold.ttf
  assets/fonts/OpenDyslexic3-Regular.ttf
  assets/fonts/OpenSans-Bold.ttf
  assets/fonts/OpenSans-Regular.ttf
  assets/fonts/OpenSans-SemiBold.ttf
  eas.json
  hooks/Fonts.ts
  lib/Analytics.ts
  lib/Analytics.tsx
  lib/Haptics.tsx
  lib/JSONSerializable.ts
  lib/Sentry.ts
  metro.config.js
  package-lock.json
  package.json
  screens/EventDetails/EventMapSnippet.tsx
  screens/ExploreEvents/Map.tsx
  tests/AmplifyAnalytics.test.ts
Labels: reviews (1)

#149 Remove dependencies system
  lib/dependencies/DependencyHooks.tsx
  lib/dependencies/DependencyKey.ts
  lib/dependencies/DependencyValues.ts
  lib/dependencies/index.ts
  tests/dependencies/DependencyHooks.test.tsx
  tests/dependencies/DependencyValues.test.ts
  tests/dependencies/helpers.ts
Labels: reviews (1)

#147 Native Haptics
  App.tsx
  babel.config.js
  lib/Haptics.tsx
  lib/Jotai.ts
  modules/tif-haptics/android/.gitignore
  modules/tif-haptics/android/build.gradle
  modules/tif-haptics/android/src/main/AndroidManifest.xml
  modules/tif-haptics/android/src/main/java/expo/modules/tifhaptics/ContextExtensions.kt
  modules/tif-haptics/android/src/main/java/expo/modules/tifhaptics/TifHaptics.kt
  modules/tif-haptics/android/src/main/java/expo/modules/tifhaptics/TifHapticsModule.kt
  modules/tif-haptics/expo-module.config.json
  modules/tif-haptics/index.ts
  modules/tif-haptics/ios/TifHaptics.podspec
  modules/tif-haptics/ios/TifHaptics.swift
  modules/tif-haptics/ios/TifHapticsModule.swift
  modules/tif-haptics/src/TifHapticsModule.ts
  package-lock.json
  package.json
  tests/Haptics.test.ts
  tests/Haptics.test.tsx
  tests/components/HexColorPicker.test.tsx
  tests/events/EventForm/EventFormScreen.test.tsx
  tests/helpers/Haptics.ts
  tsconfig.json
Labels: reviews (0)

#148 Readme update
  README.md
Labels: reviews (0)

#150 Move auth stuff into shared auth module
  auth/ChangePassword.test.tsx
  auth/ChangePasswordForm.tsx
  auth/Password.test.ts
  auth/Password.ts
  auth/index.ts
  babel.config.js
  lib/Password.ts
  screens/ProfileScreen/Navigation/ProfileScreensNavigation.tsx
  tsconfig.json
Labels: reviews (0)

#151 Fix test infrastructure + React Query
  auth/ChangePassword.test.tsx
  auth/ChangePasswordForm.tsx
  components/TiFQueryClientProvider.tsx
  hooks/Geocoding.tsx
  hooks/UserLocation.tsx
  hooks/useApiQuery.ts
  lib/ReactQuery.ts
  package-lock.json
  package.json
  screens/EventAttendeesList/AttendeesListScreen.tsx
  screens/EventFormScreen.tsx
  screens/ExploreEvents/models.ts
  screens/ExploreEvents/useExploreEvents.ts
  screens/LocationSearch/Picker.tsx
  tests/Haptics.test.tsx
  tests/Reporting.test.tsx
  tests/events/EventForm/EventFormScreen.test.tsx
  tests/events/EventForm/LocationBanner.test.tsx
  tests/events/ExploreEvents.test.tsx
  tests/helpers/Alerts.ts
  tests/helpers/ReactQuery.tsx
  tests/helpers/Timers.ts
  tests/location/LocationSearch.test.tsx
Labels: reviews (0)

#153 Make Location Search Icons a Shared Component
  components/common/Icons.tsx
  screens/LocationSearch/Icon.tsx
  screens/LocationSearch/Picker.tsx
  screens/LocationSearch/SearchResultView.tsx
  screens/LocationSearch/index.ts
Labels: reviews (1)

#152 Filled text field components
  components/TextFields.tsx
Labels: reviews (0)
