Repository tifapp/FitnessProject, pull requests merged in 2023-12, with the labels that each got.

#185 eas build action
  .easignore
  .github/workflows/auto-PR-to-main.yml
  .github/workflows/build.yml
  .github/workflows/storybook-build.yml
  app.config.js
  eas.json
  easbuild.mjs
  package-lock.json
  package.json
Labels: reviews (0)

#203 Use formdata + fix missing dependencies in github action
  .github/workflows/auto-PR-to-main.yml
  easbuild.mjs
Labels: reviews (0)

#205 Possible Fix for EAS Build Action
  .github/workflows/auto-PR-to-main.yml
  .gitignore
  .graphqlconfig.yml
  app.config.js
  easbuild.mjs
  jest/setupInfraEnv.js
  test-helpers/AdminAuthVerification.ts
Labels: reviews (1)

#204 Publicize LastRefreshTime class
  event-details/arrival-tracking/Refresh.test.ts
  event-details/arrival-tracking/Refresh.ts
Labels: reviews (0)

#206 Travel Estimates Logic
  event-details/travel-estimates/DistanceEvaluator.test.tsx
  event-details/travel-estimates/DistanceEvaluator.ts
  event-details/travel-estimates/index.ts
Labels: reviews (3)

#197 AuthNavigation stack + folder restructure
  App.tsx
  api-client/TiFAPI.ts
  auth/sign-in/Authenticator.ts
  babel.config.js
  event-details/EventScreensNavigation.tsx
  root-feature/AppView.tsx
  root-feature/Navigation/AuthNavigation.tsx
  root-feature/Navigation/TabNavigation.tsx
  root-feature/linkingConfig.test.ts
  root-feature/linkingConfig.ts
  screens/testScreens/TestChatRoomScreen.tsx
  screens/testScreens/TestEventFormScreen.tsx
  screens/testScreens/TestNotifScreen.tsx
  stacks/ActivitiesStack.tsx
  tsconfig.json
Labels: reviews (1)

#208 Update react-native-dotenv config
  .github/workflows/build.yml
  .github/workflows/storybook-build.yml
  api-client/TiFAPI.ts
  babel.config.js
  jest.config.js
  lib/Analytics.tsx
  lib/Sentry.ts
  types/env.d.ts
  types/falsey.d.ts
Labels: reviews (1)

#209 Eas build fix
  .github/workflows/auto-PR-to-main.yml
  easbuild.mjs
  screens/ProfileScreen/Navigation/ProfileScreensNavigation.tsx
Labels: reviews (1)

#207 Make event arrival radius dynamic
  event-details/arrival-tracking/Geofencing.ts
  event-details/arrival-tracking/MockData.ts
  event-details/arrival-tracking/Models.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
Labels: reviews (0)

#211 Add aws-amplify/react-native package
  auth/CognitoHelpers.ts
  auth/forgot-password/Environment.test.tsx
  auth/sign-in/Authenticator.test.ts
  auth/sign-in/Navigation.test.tsx
  auth/sign-up/Environment.test.ts
  jest.config.js
  package-lock.json
  package.json
Labels: reviews (0)

#210 Event Arrivals: API Integration
  api-client/TiFAPI.ts
  babel.config.js
  event-details/arrival-tracking/ArrivalsOperation.test.ts
  event-details/arrival-tracking/ArrivalsOperation.ts
  event-details/arrival-tracking/Geofencing.ts
  event-details/arrival-tracking/MockData.ts
  event-details/arrival-tracking/Models.ts
  event-details/arrival-tracking/Refresh.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/UpcomingArrivals.ts
  event-details/arrival-tracking/index.ts
  event-details/travel-estimates/DistanceEvaluator.test.tsx
  event-details/travel-estimates/DistanceEvaluator.ts
  location/MockData.ts
  location/Region.ts
  location/index.ts
  location/search/Models.ts
  location/search/RecentsStorage.ts
  shared-models/Event.ts
  shared-models/EventArrivals.ts
  shared-models/Location.test.ts
  shared-models/Location.ts
  shared-models/Placemark.test.ts
  shared-models/Placemark.ts
  tsconfig.json
Labels: reviews (1)

#212 Add .env to eas build
  .github/workflows/auto-PR-to-main.yml
Labels: reviews (0)

#213 Event details remove old UI
  event-details/AttendeeSection.tsx
  event-details/ChatSection.tsx
  event-details/EventDetails.tsx
  event-details/EventMapSnippet.tsx
  event-details/EventScreensNavigation.tsx
  event-details/LocationSection.tsx
  event-details/MenuDropdown.test.tsx
  event-details/MenuDropdown.tsx
  event-details/TimeSection.tsx
Labels: reviews (1)
