Repository tifapp/FitnessProject, pull requests merged in 2023-05, with the labels that each got.

#107 Map Update + Styling Changes
  assets/Windows_10_Default_Profile_Picture.svg.png
  components/EventsList.tsx
  components/eventMap/EventMarker.tsx
  components/eventMap/EventsMap.tsx
  components/tabBarComponents/EventTabBar.tsx
  hooks/UserLocation.ts
  lib/events/Event.ts
  lib/location/UserLocation.ts
  screens/ActivitiesScreen.tsx
  screens/EventAttendeesList/AttendeesListScreen.tsx
  screens/EventAttendeesList/attendeeEntry.tsx
  tests/components/Map.test.tsx
  tests/location/LocationSearch.test.tsx
Labels: merge conflict, reviews (), reviews (4)

#111 Reporting UI
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/ContentReporting/ContentReporting.stories.tsx
  amplify/backend/api/fitnessprojectapi/cli-inputs.json
  amplify/backend/api/fitnessprojectapi/custom-roles.json
  amplify/backend/api/fitnessprojectapi/resolvers/Mutation.deleteEvent.auth.1.res.vtl
  amplify/backend/api/fitnessprojectapi/resolvers/Query.findEvents.req.vtl
  amplify/backend/api/fitnessprojectapi/schema/eventsschema.graphql
  amplify/backend/api/fitnessprojectapi/schema/locationschema.graphql
  amplify/backend/function/LogScheduledNotifications/LogScheduledNotifications-cloudformation-template.json
  amplify/backend/function/LogScheduledNotifications/amplify.state
  amplify/backend/function/LogScheduledNotifications/custom-policies.json
  amplify/backend/function/LogScheduledNotifications/function-parameters.json
  amplify/backend/function/LogScheduledNotifications/parameters.json
  amplify/backend/function/LogScheduledNotifications/src/event.json
  amplify/backend/function/LogScheduledNotifications/src/index.js
  amplify/backend/function/LogScheduledNotifications/src/package-lock.json
  amplify/backend/function/LogScheduledNotifications/src/package.json
  amplify/backend/function/eventNotifications/amplify.state
  amplify/backend/function/eventNotifications/custom-policies.json
  amplify/backend/function/eventNotifications/eventNotifications-cloudformation-template.json
  amplify/backend/function/eventNotifications/function-parameters.json
  amplify/backend/function/eventNotifications/parameters.json
  amplify/backend/function/eventNotifications/src/event.json
  amplify/backend/function/eventNotifications/src/index.js
  amplify/backend/function/eventNotifications/src/package-lock.json
  amplify/backend/function/eventNotifications/src/package.json
  amplify/backend/geo/placeIndex69179812/cli-inputs.json
  amplify/backend/geo/placeIndex69179812/parameters.json
  amplify/backend/geo/placeIndex69179812/placeIndex69179812-cloudformation-template.json
  amplify/backend/geo/placeindexa53d0303/cli-inputs.json
  amplify/backend/geo/placeindexa53d0303/parameters.json
  amplify/backend/geo/placeindexa53d0303/placeindexa53d0303-cloudformation-template.json
  components/Navigation.tsx
  lib/Reporting.ts
  lib/String.ts
  lib/events/Event.ts
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
  screens/Reporting/FormView.tsx
  screens/Reporting/Navigation.tsx
  screens/Reporting/SuccessView.tsx
  screens/Reporting/index.ts
  tests/Reporting.test.tsx
  tests/components/Map.test.tsx
  tests/location/LocationSearch.test.tsx
Labels: reviews (2)

#112 Navigation Basis
  App.tsx
  components/EventsList.tsx
  components/eventMap/EventMarker.tsx
  components/headerComponents/headerOptions.tsx
  screens/ActivitiesScreen.tsx
  screens/ActivitiesScreenNavWrapper.tsx
  screens/EventDetails/EventDetails.tsx
  screens/EventDetailsScreenNavWrapper.tsx
  screens/EventFormScreenNavWrapper.tsx
  stacks/ActivitiesStack.tsx
Labels: reviews (3)

#116 Add a URL/User handle rendering text component
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/ContentText/ContextText.stories.tsx
  components/ContentText.tsx
  lib/Linkify.ts
  lib/String.ts
  lib/users/User.ts
  package-lock.json
  package.json
  tests/components/ContentText.test.tsx
Labels: reviews (2)

#113 Event Details Rework
  components/Text.tsx
  components/bottomTabComponents/AttendanceButton.tsx
  components/bottomTabComponents/EventTabBar.tsx
  components/common/Buttons.tsx
  components/common/Toasts.tsx
  components/eventCard/EventCard.tsx
  components/eventCard/MenuDropdown.tsx
  components/profileImageComponents/ProfileImage.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  components/profileImageComponents/ProfileImageAndNameWithFriend.tsx
  components/tabBarComponents/EventTabBar.tsx
  lib/AppColorStyle.ts
  lib/ButtonStyle.ts
  lib/Calendar.ts
  lib/NativeMap.ts
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
  screens/EventDetails/AttendeeSection.tsx
  screens/EventDetails/ChatSection.tsx
  screens/EventDetails/EventDetails.tsx
  screens/EventDetails/ExpandableText.tsx
  screens/EventDetails/LocationSection.tsx
  screens/EventDetails/TimeSection.tsx
  screens/Reporting/SuccessView.tsx
Labels: reviews (3)

#114 API Client fetching fix + error codes
  api-client/APIClient.test.ts
  api-client/api-client.ts
  api-client/api-endpoint-types.ts
  api-client/api-schema.ts
  api-client/aws-fetch.ts
  api-client/index.ts
  babel.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: reviews (2)

#118 Fix CI
  lib/dependencies/DependencyValues.ts
  tests/dependencies/helpers.ts
Labels: reviews (2)

#108 Expo Upgrade SDK 48
  jest.config.js
  jest/setupAssetMocks.js
  package-lock.json
  package.json
  tests/events/EventForm/EventFormScreen.test.tsx
Labels: reviews (2)

#119 Fixed package versions for expo 48
  lib/uuid.ts
  package-lock.json
  package.json
Labels: reviews (1)

#117 Settings Screen UI
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  .storybook/components/ContentReporting/ContentReporting.stories.tsx
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  App.tsx
  components/EventsList.tsx
  components/bottomTabComponents/BottomNavTabBar.tsx
  components/bottomTabComponents/EventTabBar.tsx
  components/common/Icons.tsx
  components/eventCard/MenuDropdown.tsx
  components/profileImageComponents/ConfirmationDialogue.tsx
  components/profileImageComponents/ProfileImage.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
  screens/EventAttendeesList/AttendeesListScreen.tsx
  screens/EventAttendeesList/attendeeEntry.tsx
  screens/EventDetails/AttendeeSection.tsx
  screens/EventDetails/ChatSection.tsx
  screens/EventDetails/EventDetails.tsx
  screens/EventDetails/LocationSection.tsx
  screens/SettingsScreen/PrivacyPolicy.tsx
  screens/SettingsScreen/SettingsScreen.tsx
  screens/TestProfileScreen.tsx
  screens/testScreens/TestChatRoomScreen.tsx
  screens/testScreens/TestNotifScreen.tsx
  stacks/ActivitiesStack.tsx
Labels: reviews (3)

#120 Profile Screen
  components/bottomTabComponents/BottomNavTabBar.tsx
  components/common/Buttons.tsx
  components/common/ExpandableText.tsx
  components/common/Toasts.tsx
  components/eventCard/EventCard.tsx
  components/profileImageComponents/ProfileImageAndNameWithFriend.tsx
  lib/Calendar.ts
  lib/User.ts
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
  screens/EventDetails/EventDetails.tsx
  screens/EventDetails/LocationSection.tsx
  screens/EventDetails/TimeSection.tsx
  screens/ProfileScreen/AllEventsModal.tsx
  screens/ProfileScreen/EventCarousel.tsx
  screens/ProfileScreen/ProfileScreen.tsx
  screens/ProfileScreen/ProfileScreenNavWrapper.tsx
  stacks/ActivitiesStack.tsx
Labels: reviews (2)

#121 React query wrapper for api client
  api-client/APIClient.test.ts
  api-client/api-client.ts
  api-client/api-endpoint-types.ts
  api-client/api-schema.ts
  hooks/useApiQuery.ts
  screens/ActivitiesScreenNavWrapper.tsx
Labels: reviews (3)
