Repository tifapp/FitnessProject, pull requests merged in 2023-07, with the labels that each got.

#130 upgrade node version
  .github/workflows/build.yml
Labels: reviews (1)

#129 Markdown implementation + Major Frontend README changes
  README.md
Labels: reviews (0)

#128 Add code style guide
  STYLEGUIDE.md
Labels: reviews (1)

#126 Explore Events UI
  .github/workflows/build.yml
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/Explore/Explore.stories.tsx
  App.tsx
  components/Text.tsx
  components/bottomTabComponents/BottomNavTabBar.tsx
  components/eventCard/EventCard.tsx
  components/eventCard/SkeletonEventCard.tsx
  components/eventMap/EventMarker.tsx
  components/eventMap/EventsMap.tsx
  components/profileImageComponents/ProfileImage.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  components/profileImageComponents/ProfileImageAndNameWithFriend.tsx
  hooks/UserLocation.ts
  lib/Cancellable.ts
  lib/DelayData.ts
  lib/DelayData.tsx
  lib/Math.ts
  lib/Random.ts
  lib/ReactQuery.ts
  lib/events/Event.ts
  lib/location/Location.ts
  lib/location/Region.ts
  lib/location/index.ts
  lib/users/User.ts
  lib/users/index.ts
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
  screens/ActivitiesScreenNavWrapper.tsx
  screens/EventDetails/EventDetails.tsx
  screens/EventDetails/EventScreensNavigation.tsx
  screens/ExploreEvents/BottomSheet.tsx
  screens/ExploreEvents/ExploreView.tsx
  screens/ExploreEvents/Map.tsx
  screens/ExploreEvents/MapMarker.tsx
  screens/ExploreEvents/Navigation.tsx
  screens/ExploreEvents/SearchBar.tsx
  screens/ExploreEvents/index.ts
  screens/ExploreEvents/models.ts
  screens/ExploreEvents/useExploreEvents.ts
  stacks/ActivitiesStack.tsx
  tests/events/EventCard/EventCard.test.tsx
  tests/events/ExploreEvents.test.tsx
  tests/helpers/Cancellable.ts
  tests/location/Region.test.ts
Labels: reviews (4)

#132 Generic text field
  .eslintrc.json
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/SearchBar/SearchBar.stories.tsx
  .storybook/components/TextField/TextField.stories.tsx
  components/SearchBar.tsx
  components/Text.tsx
  components/TextFields.tsx
Labels: reviews (0)

#133 Add accessibility label to Password text field
  components/TextFields.tsx
Labels: reviews (1)

#134 Make password visibility internal
  .storybook/components/TextField/TextField.stories.tsx
  components/TextFields.tsx
Labels: reviews (0)

#131 Upgrade storybook expo
  .storybook/package-lock.json
  .storybook/package.json
  package.json
Labels: reviews (0)

#135 Slim App component
  App.tsx
  components/AppQueryClientProvider.tsx
  components/TiFMenuProvider.tsx
  components/TiFQueryClientProvider.tsx
Labels: reviews (2)

#124 Change-password
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/ChangePassword/ChangePasswordScreen.stories.tsx
  components/common/Buttons.tsx
  components/eventForm/TextField.tsx
  lib/DelayData.ts
  lib/Password.ts
  screens/EventAttendeesList/AttendeesListScreen.tsx
  screens/ProfileScreen/Navigation/ProfileScreensNavigation.tsx
  screens/SettingsScreen/SettingsScreen.tsx
  screens/changePassword/ChangePasswordForm.tsx
  stacks/ActivitiesStack.tsx
  tests/ChangePassword.test.tsx
  tests/Password.test.ts
Labels: reviews (0)

#137 Remove unused Storybook Stories
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  .storybook/components/Button/Button.stories.tsx
  .storybook/components/Button/Button.tsx
  .storybook/components/ChangePassword/ChangePasswordScreen.stories.tsx
  .storybook/components/DateTimePicker/DateTimePicker.stories.tsx
  .storybook/components/EventForm/EventForm.stories.tsx
  .storybook/components/EventFormToolbar/EventFormToolbar.stories.tsx
  .storybook/components/Explore/Explore.stories.tsx
  .storybook/components/HexColorPicker/HexColorPicker.stories.tsx
  .storybook/components/IconButton/IconButton.stories.tsx
  .storybook/components/LocationSearchResultRow/LocationSearchResultRow.stories.tsx
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
Labels: reviews (0)

#138 Simplify user location logic
  .storybook/components/Explore/Explore.stories.tsx
  App.tsx
  hooks/UserLocation.ts
  hooks/UserLocation.tsx
  lib/NativeMap.ts
  lib/OpenInMaps.ts
  lib/Random.ts
  lib/location/ExpoHelpers.ts
  lib/location/Geocoding.ts
  lib/location/Location.ts
  lib/location/RecentsStorage.ts
  lib/location/Search.ts
  lib/location/UserLocation.ts
  lib/location/index.ts
  screens/EventDetails/EventDetails.tsx
  screens/EventDetails/LocationSection.tsx
  screens/ExploreEvents/useExploreEvents.ts
  screens/LocationSearch/Picker.tsx
  tests/events/ExploreEvents.test.tsx
  tests/location/LocationSearch.test.tsx
  tests/location/RecentsStorage.test.ts
  tests/location/UserLocation.test.ts
  tests/location/UserLocationHooks.test.tsx
Labels: reviews (1)
