Repository tifapp/FitnessProject, pull requests merged in 2023-04, with the labels that each got.

#70 Add github action to set up project files
  .github/workflows/auto-label.yml
  .github/workflows/build.yml
  .husky/pre-commit
  components/eventForm/EventFormValues.ts
  package-lock.json
  package.json
  tests/events/EventForm/EventFormScreen.test.tsx
  tests/events/EventForm/LocationBanner.test.tsx
  tests/events/EventForm/helpers.ts
  tests/location/search/AsyncStorageSearchHistory.test.ts
Labels: reviews (0)

#91 UI for the Event Tab Bar
  components/EventsList.tsx
  components/tabBarComponents/EventTabBar.tsx
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
Labels: merge conflict, reviews ()

#92 Add Open Sans font
  App.tsx
  components/common/Icons.tsx
  components/eventForm/BottomSheet.tsx
  components/eventForm/DismissButton.tsx
  components/eventForm/LocationBanner.tsx
  components/eventForm/SectionHeader.tsx
  components/eventForm/SubmitButton.tsx
  components/eventForm/TextField.tsx
  components/eventForm/Toolbar.tsx
  components/formComponents/FormLabels.tsx
  hooks/Fonts.ts
  package-lock.json
  package.json
Labels: merge conflict, reviews (0), reviews ()

#95 New Location Type
  lib/location/Location.ts
  lib/location/Placemark.ts
Labels: merge conflict, reviews (0), reviews ()

#96 OpenSans Text Components
  components/Text.tsx
Labels: merge conflict, reviews (0), reviews ()

#97 Install Faker.js and React Native Fast Image
  package-lock.json
  package.json
Labels: merge conflict, reviews (0), reviews ()

#90 Reworked UI for Event Card
  App.tsx
  app.json
  assets/fonts/OpenSans-Bold.ttf
  assets/fonts/OpenSans-Regular.ttf
  components/EventsList.tsx
  components/eventCard/EventCard.tsx
  components/eventCard/MenuDropdown.tsx
  lib/date/DateRange.ts
  lib/location/Placemark.ts
  package-lock.json
  package.json
  tests/events/EventCard/EventCard.test.tsx
Labels: merge conflict, reviews ()

#94 Map Split + EventDetails Map
  app.json
  assets/Solid_white.svg.png
  components/EventsMap.tsx
  components/MapTestData.tsx
  components/eventDetails/EventDetails.tsx
  components/eventDetails/EventMapSnippet.tsx
  screens/ActivitiesScreen.tsx
  tests/components/Map.test.tsx
Labels: merge conflict, reviews (0), reviews ()

#102 Location Search UI
  components/SearchBar.tsx
  components/Text.tsx
  components/common/Icons.tsx
  components/eventForm/LocationBanner.tsx
  components/locationSearch/SearchResultRow.tsx
  components/locationSearch/index.ts
  hooks/Geocoding.ts
  hooks/UserLocation.ts
  jest.config.js
  jest/setupKeyboardAwareMock.jsx
  lib/DistanceFormatting.ts
  lib/Jotai.ts
  lib/Math.ts
  lib/NullsToUndefined.ts
  lib/Random.ts
  lib/location/Geocoding.ts
  lib/location/Location.ts
  lib/location/Placemark.ts
  lib/location/UserLocation.ts
  package-lock.json
  package.json
  screens/LocationSearch/Data.ts
  screens/LocationSearch/Picker.tsx
  screens/LocationSearch/SearchBar.tsx
  screens/LocationSearch/SearchResultView.tsx
  screens/LocationSearch/SearchResultsList.tsx
  screens/LocationSearch/index.ts
  screens/LocationSearch/state.ts
  tests/DistanceFormatting.test.ts
  tests/NullsToUndefined.test.ts
  tests/events/EventForm/EventFormScreen.test.tsx
  tests/events/EventForm/LocationBanner.test.tsx
  tests/helpers/ReactQuery.tsx
  tests/location/AsyncStorageSearchHistory.test.ts
  tests/location/LocationSearch.test.tsx
  tests/location/UserLocationHooks.test.tsx
Labels: merge conflict, reviews (0), reviews ()

#105 Current User Coordinates Expo Query
  hooks/UserLocation.ts
  lib/location/UserLocation.ts
  tests/location/UserLocation.test.ts
Labels: merge conflict, reviews (0), reviews ()

#101 Button Components Shown in Design
  components/common/Buttons.tsx
  lib/ButtonStyle.ts
Labels: merge conflict, reviews (0)

#104 Recent Locations Storage
  lib/Array.ts
  lib/AsyncStorage.ts
  lib/location/Location.ts
  lib/location/RecentsStorage.ts
  lib/location/Search.ts
  lib/location/index.ts
  lib/location/search/History.ts
  lib/location/search/Result.ts
  lib/location/search/index.ts
  package-lock.json
  package.json
  screens/LocationSearch/Data.ts
  screens/LocationSearch/SearchResultView.tsx
  screens/LocationSearch/SearchResultsList.tsx
  tests/ArrayUtils.test.ts
  tests/AsyncStorageUtils.test.ts
  tests/helpers/Timers.ts
  tests/location/AsyncStorageSearchHistory.test.ts
  tests/location/LocationSearch.test.tsx
  tests/location/RecentsStorage.test.ts
Labels: merge conflict, reviews (0), reviews ()

#100 Storybook custom UI
  .storybook/.ondevice/Storybook.tsx
  .storybook/App.tsx
  .storybook/components/Button/Button.tsx
Labels: merge conflict, reviews (0), reviews ()

#98 Fix labelling github action
  .github/workflows/auto-label.yml
Labels: reviews (0)

#109 Add code example docs for useTrackUserLocation
  hooks/UserLocation.ts
Labels: reviews (1)

#106 API Client
  .eslintrc.json
  .gitignore
  api-client/APIClient.test.ts
  api-client/api-client.ts
  api-client/api-endpoint-types.ts
  api-client/api-schema.ts
  api-client/aws-fetch.ts
  api-client/index.ts
  app.config.ts
  app.json
  babel.config.js
  components/loginComponents/SignIn.tsx
  global.d.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: merge conflict, reviews (), reviews (2)

#110 Event Details - Redesign and Functionality
  App.tsx
  app.config.ts
  assets/Solid_white.svg.png
  components/EventsList.tsx
  components/common/Buttons.tsx
  components/eventCard/EventCard.tsx
  components/eventCard/MenuDropdown.tsx
  components/eventDetails/EventDetails.tsx
  lib/ButtonStyle.ts
  lib/Calendar.ts
  lib/ExternalMap.ts
  lib/date/DateRange.ts
  lib/events/Event.ts
  package-lock.json
  package.json
  screens/ActivitiesScreen.tsx
  screens/EventDetails/AttendeeSection.tsx
  screens/EventDetails/ChatSection.tsx
  screens/EventDetails/EventDetails.tsx
  screens/EventDetails/EventMapSnippet.tsx
  screens/EventDetails/ExpandableText.tsx
  screens/EventDetails/LocationSection.tsx
  screens/EventDetails/TimeSection.tsx
Labels: reviews (2)
