Repository tifapp/FitnessProject, pull requests merged in 2023-11, with the labels that each got.

#179 Event Details: Remove System Calendar Integration
  event-details/Calendar.ts
  event-details/Event.ts
  event-details/EventDetails.tsx
  event-details/LocationSection.tsx
  event-details/OpenInMaps.ts
  event-details/TimeSection.tsx
Labels: reviews (1)

#182 Update button components
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/Buttons/Buttons.stories.tsx
  auth/AuthLayout.tsx
  components/Buttons.tsx
  components/bottomTabComponents/AttendanceButton.tsx
  components/bottomTabComponents/BottomTabButton.tsx
  components/common/Buttons.tsx
  screens/ExploreEvents/ExploreView.tsx
  screens/ProfileScreen/ProfileView.tsx
  screens/Reporting/SuccessView.tsx
Labels: reviews (0)

#183 Search Client Module Logic
  .storybook/components/LocationSearch/LocationSearch.stories.tsx
  lib/location/Location.ts
  location-search/LocationSearch.test.tsx
  location-search/Picker.tsx
  location-search/SearchClient.test.ts
  location-search/SearchClient.ts
  location-search/SearchResultView.tsx
  location-search/mocks.ts
  location-search/models.ts
  location-search/state.ts
Labels: reviews (0)

#184 Event Handle New Format + Cleanup Linkify Parsing
  components/ContentText.test.tsx
  components/ContentText.tsx
  event-details/Event.test.ts
  event-details/Event.ts
  lib/users/UserHandle.ts
Labels: reviews (0)

#186 Read more text
  .storybook/components/ContentText/ContextText.stories.tsx
  components/ContentText.tsx
  lib/Reanimated.ts
Labels: reviews (0)

#187 AuthBanner logic + tests
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  auth/forgot-password/ForgotPasswordNavigation.test.tsx
  auth/session/AuthBanner.test.tsx
  auth/session/AuthBanner.tsx
  auth/session/UserSessionContext.tsx
  auth/session/index.ts
Labels: reviews (0)

#188 Content Parsing module
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/ContentText/ContextText.stories.tsx
  .storybook/components/TextField/TextField.stories.tsx
  api-client/TiFAPI.ts
  auth/sign-up/ChangeUserHandle.test.tsx
  auth/sign-up/ChangeUserHandle.tsx
  auth/sign-up/Environment.test.ts
  auth/sign-up/Environment.ts
  auth/sign-up/Navigation.test.tsx
  auth/sign-up/Navigation.tsx
  babel.config.js
  components/ContentText.tsx
  content-parsing/ContentText.test.tsx
  content-parsing/ContentText.tsx
  content-parsing/EventHandle.test.ts
  content-parsing/EventHandle.ts
  content-parsing/ExpandableContentText.tsx
  content-parsing/Linkify.ts
  content-parsing/UserHandle.test.ts
  content-parsing/UserHandle.ts
  content-parsing/index.ts
  event-details/Event.test.ts
  event-details/Event.ts
  lib/Linkify.ts
  lib/users/index.ts
  screens/ProfileScreen/EditProfileScreen/EditProfileView.tsx
  tsconfig.json
Labels: reviews (0)

#189 Admin confirm sign-up for testing
  package-lock.json
  package.json
  tests/helpers/AdminAuthVerification.ts
Labels: reviews (0)

#191 Add color to Event Handles
  .storybook/components/ContentText/ContextText.stories.tsx
  content-parsing/ContentText.test.tsx
  content-parsing/ContentText.tsx
  content-parsing/EventHandle.test.ts
  content-parsing/EventHandle.ts
  lib/AppColorStyle.ts
  lib/Color.test.ts
  lib/Color.ts
Labels: reviews (0)

#192 Background Location Permissions Setup
  .storybook/components/Explore/Explore.stories.tsx
  .storybook/components/LocationSearch/LocationSearch.stories.tsx
  App.tsx
  app.config.ts
  hooks/UserLocation.tsx
Labels: reviews (1)

#195 Auto dev to main
  .github/workflows/auto-PR-to-main.yml
Labels: reviews (0)

#171 Add timeout to unit tests
  .github/workflows/build.yml
Labels: reviews (1)

#194 Arrivals: Refresh Policy
  event-details/arrival-tracking/Refresh.test.ts
  event-details/arrival-tracking/Refresh.ts
  lib/date/Date.ts
  lib/date/DateRange.ts
  lib/date/dayjs.ts
Labels: reviews (1)

#196 Arrivals: Geofencing
  App.tsx
  event-details/arrival-tracking/Geofencing.ts
  event-details/arrival-tracking/index.ts
  lib/Math.ts
  package-lock.json
  package.json
Labels: reviews (1)

#199 Arrivals: Handle Geofencing Update
  event-details/arrival-tracking/Geofencing.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/models.ts
  lib/location/Location.ts
Labels: reviews (1)

#193 Arrivals: EventArrivalsTracker
  App.tsx
  event-details/arrival-tracking/Geofencing.ts
  event-details/arrival-tracking/Refresh.test.ts
  event-details/arrival-tracking/Refresh.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/UpcomingArrivals.ts
  event-details/arrival-tracking/index.ts
  event-details/arrival-tracking/models.ts
  lib/AsyncStorage.ts
  lib/Math.ts
  lib/date/Date.ts
  lib/date/DateRange.ts
  lib/date/dayjs.ts
  lib/location/Location.ts
  package-lock.json
  package.json
Labels: reviews (2)
