Repository tifapp/FitnessProject, pull requests merged in 2024-05, with the labels that each got.

#298 Settings: Genericize Settings Store
  arrival-tracking/Refresh.test.ts
  arrival-tracking/Refresh.ts
  modules/tif-haptics/src/TifHapticsModule.tsx
  settings-storage/Hooks.tsx
  settings-storage/LocalSettings.test.ts
  settings-storage/LocalSettings.ts
  settings-storage/PersistentStore.test.ts
  settings-storage/PersistentStore.ts
  settings-storage/Settings.test.ts
  settings-storage/Settings.ts
Labels: reviews (1)

#299 User Settings Sync
  lib/SQLite.ts
  package-lock.json
  package.json
  settings-storage/Hooks.tsx
  settings-storage/PersistentStore.ts
  settings-storage/UserSettings.test.ts
  settings-storage/UserSettings.ts
  test-helpers/SQLite.ts
Labels: reviews (3)

#311 Settings: Selectors
  package-lock.json
  package.json
  settings-storage/Hooks.tsx
Labels: reviews (1)

#313 Auto ticket link
  .env.infra.template
  .github/workflows/link-ticket-on-pull-request.yml
  package.json
  tsconfig.json
Labels: reviews (1)

#316 trigger ticket link github action when pr is edited
  .github/workflows/link-ticket-on-pull-request.yml
Labels: reviews (1)

#317 Remove a few ESLint Styling Rules
  .eslintrc.json
Labels: reviews (0)

#320 Settings: Update Storage
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  lib/SQLite.ts
  settings-storage/LocalSettings.ts
  settings-storage/PersistentStore.test.ts
  settings-storage/PersistentStores.ts
  settings-storage/UserSettings.ts
Labels: reviews (0)

#321 Settings: Appearance Settings
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  lib/Fonts.ts
  settings-boundary/AppearanceSettings.tsx
  settings-boundary/components/ScrollView.tsx
  settings-boundary/components/Section.tsx
  settings-boundary/index.ts
Labels: reviews (1)

#322 Move `EmailAddress`, `USPhoneNumber`, and `PrivacyFormattable` into `user` module.
  auth-boundary/ChangePassword.test.tsx
  auth-boundary/ChangePassword.tsx
  auth-boundary/EmailPhoneText.tsx
  auth-boundary/Models.test.ts
  auth-boundary/Models.ts
  auth-boundary/Password.test.ts
  auth-boundary/Password.ts
  auth-boundary/VerifyCode.tsx
  auth-boundary/forgot-password/Environment.test.tsx
  auth-boundary/forgot-password/Environment.ts
  auth-boundary/forgot-password/ForgotPasswordForm.test.tsx
  auth-boundary/forgot-password/ForgotPasswordForm.tsx
  auth-boundary/index.ts
  auth-boundary/sign-in/Authenticator.test.ts
  auth-boundary/sign-in/Authenticator.ts
  auth-boundary/sign-in/SignInForm.test.tsx
  auth-boundary/sign-in/SignInForm.tsx
  auth-boundary/sign-up/CredentialsForm.tsx
  auth-boundary/sign-up/Environment.test.ts
  auth-boundary/sign-up/Environment.ts
  core-root/navigation/auth/ForgotPassword.test.tsx
  core-root/navigation/auth/ForgotPassword.tsx
  core-root/navigation/auth/SignIn.test.tsx
  core-root/navigation/auth/SignIn.tsx
  core-root/navigation/auth/SignUp.tsx
  user/privacy/EmailAddress.test.ts
  user/privacy/EmailAddress.ts
  user/privacy/PrivacyFormattable.ts
  user/privacy/USPhoneNumber.test.ts
  user/privacy/USPhoneNumber.ts
  user/privacy/index.ts
Labels: reviews (0)

#326 True Dismissal
  lib/AppState.tsx
  lib/utils/UseDismisaal.test.tsx
  lib/utils/UseDismissal.ts
Labels: reviews (1)

#327 Logs + Main SQLite DB separation
  .eslintrc.json
  lib/SQLite.ts
  lib/Sqlite.test.ts
  test-helpers/SQLite.ts
Labels: reviews (0)

#315 Settings: Privacy Settings + Initial Settings Components
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  auth-boundary/AuthTextFields.tsx
  babel.config.js
  components/Divider.tsx
  components/TextFields.tsx
  components/profileImageComponents/ProfileImageAndNameWithFriend.tsx
  core-root/navigation/TabBar.tsx
  ios/Podfile.lock
  lib/AppColorStyle.ts
  settings-boundary/PrivacySettings.test.tsx
  settings-boundary/PrivacySettings.tsx
  settings-boundary/components/Card.tsx
  settings-boundary/components/NamedIconRow.tsx
  settings-boundary/components/NavigationLink.tsx
  settings-boundary/components/Section.tsx
  settings-boundary/components/Switch.tsx
  settings-boundary/components/ToggleCard.tsx
  settings-boundary/index.ts
  settings-storage/Hooks.tsx
  settings-storage/UserSettings.ts
  tsconfig.json
Labels: reviews (0)

#324 Settings: General
  .eslintrc.json
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  lib/AppState.tsx
  lib/SQLite.ts
  lib/Sqlite.test.ts
  lib/utils/UseDismisaal.test.tsx
  lib/utils/UseDismissal.ts
  modules/tif-haptics/src/TifHapticsModule.tsx
  settings-boundary/GeneralSettings.test.tsx
  settings-boundary/GeneralSettings.tsx
  settings-boundary/components/ChecklistPicker.tsx
  settings-boundary/components/Section.tsx
  settings-boundary/index.ts
  settings-storage/LocalSettings.ts
  test-helpers/SQLite.ts
Labels: reviews (1)

#328 Settings: Block List
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  components/Text.tsx
  components/common/Toasts.tsx
  components/profileImageComponents/ProfileImage.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  event/EventCard.tsx
  package-lock.json
  package.json
  settings-boundary/BlockList.test.tsx
  settings-boundary/BlockList.tsx
  settings-boundary/MockData.ts
  settings-boundary/PrivacySettings.tsx
  settings-boundary/components/Card.tsx
  settings-boundary/components/Section.tsx
  settings-boundary/components/ToggleCard.tsx
  settings-boundary/index.ts
Labels: reviews (0)

#325 Add pull request template
  .github/workflows/pull_request_template.md
Labels: reviews (1)

#329 Settings: Fix iOS Unblock Success Banner Bug
  settings-boundary/BlockList.tsx
Labels: reviews (0)

#332 Settings: Root
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  event-details-boundary/Menu.test.tsx
  settings-boundary/RootSettings.test.tsx
  settings-boundary/RootSettings.tsx
  settings-boundary/components/NavigationLink.tsx
  settings-boundary/index.ts
  user/Session.test.tsx
  user/Session.tsx
Labels: reviews (1)
