Repository tifapp/FitnessProject, pull requests merged in 2024-01, with the labels that each got.

#220 AWS Upgrade: Cognito Secure Storage
  auth/CognitoSecureStorage.test.ts
  auth/CognitoSecureStorage.ts
  lib/SecureStore.ts
  test-helpers/InMemorySecureStore.ts
Labels: reviews (0)

#217 Cleanup Cognito Helpers
  auth/CognitoHelpers.ts
  auth/forgot-password/Environment.test.tsx
  auth/sign-in/Authenticator.test.ts
  auth/sign-in/Navigation.test.tsx
  auth/sign-up/Environment.test.ts
  test-helpers/Cognito.ts
Labels: reviews (0)

#218 Auth Upgrade: Sign Up
  api-client/TiFAPI.ts
  auth/CognitoHelpers.ts
  auth/Models.ts
  auth/sign-up/CognitoHelpers.ts
  auth/sign-up/Environment.test.ts
  auth/sign-up/Environment.ts
  auth/sign-up/Navigation.test.tsx
  content-parsing/UserHandle.ts
  package-lock.json
  package.json
Labels: reviews (0)

#219 Auth Upgrade: Sign In
  auth/sign-in/Authenticator.test.ts
  auth/sign-in/Authenticator.ts
  auth/sign-in/Navigation.test.tsx
  auth/sign-up/Environment.test.ts
Labels: reviews (0)

#221 Remove original attendees list
  screens/EventAttendeesList/AttendeesListScreen.tsx
  screens/EventAttendeesList/AttendeesMocks.tsx
  screens/EventAttendeesList/attendeeEntry.tsx
Labels: reviews (0)

#215 Remove no-use-before-define in eslint
  .eslintrc.json
  content-parsing/UserHandle.ts
  event-details/arrival-tracking/Refresh.ts
Labels: reviews (0)

#223 Eas storybook config fix
  .storybook/app.config.js
  app.config.js
  appconfighelper.js
Labels: reviews (0)

#224 Fix storybook dependencies for eas
  .github/workflows/deploy.yml
  .storybook/easbuild.mjs
  .storybook/package-lock.json
  .storybook/package.json
Labels: reviews (1)

#225 eas build script fix and .env fix
  .github/workflows/deploy.yml
  .storybook/app.config.js
  .storybook/package.json
  app.config.js
  appconfighelper.js
  easbuild.mjs
  package-lock.json
  package.json
Labels: reviews (1)

#226 Fix storybook .env.infra path
  .storybook/app.config.js
Labels: reviews (1)

#227 Add missing packages and fix .storybook env for eas
  .github/workflows/deploy.yml
  .storybook/package-lock.json
  .storybook/package.json
Labels: reviews (1)

#216 Event Arrival Banner
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/EventDetails/EventDetails.stories.tsx
  components/Buttons.tsx
  components/common/Icons.tsx
  date-time/Dayjs.ts
  event-details/arrival-tracking/ArrivalBanner.test.tsx
  event-details/arrival-tracking/ArrivalBanner.tsx
  event-details/arrival-tracking/index.ts
Labels: reviews (1)

#230 UseLoadEventDetails
  event-details/Event.ts
  event-details/EventDetailsLoading.test.tsx
  event-details/EventDetailsLoading.tsx
Labels: reviews (0)

#232 Event Details: Automatically refetch when the internet comes back up
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  App.tsx
  event-details/EventDetailsLoading.test.tsx
  event-details/EventDetailsLoading.tsx
  lib/InternetConnection.tsx
  lib/utils/UseEffectEvent.ts
  test-helpers/ExpectNeverOccurs.ts
  test-helpers/InternetConnectionStatus.ts
Labels: reviews (1)

#233 Event Details: API Integration + New Event Types
  api-client/TiFAPI.ts
  api-client/client.ts
  date-time/DateRange.ts
  event-details/Event.test.ts
  event-details/Event.ts
  event-details/EventCard.test.tsx
  event-details/EventCard.tsx
  event-details/EventDetailsLoading.test.tsx
  event-details/EventDetailsLoading.tsx
  event-details/MockData.ts
  lib/users/User.ts
  screens/ExploreEvents/BottomSheet.tsx
  screens/ExploreEvents/ExploreView.tsx
  screens/ExploreEvents/Map.tsx
  screens/ExploreEvents/Navigation.tsx
  screens/ExploreEvents/models.ts
  screens/ExploreEvents/useExploreEvents.ts
  screens/ProfileScreen/EventCarousel.tsx
  screens/ProfileScreen/EventHistoryModal.tsx
  screens/ProfileScreen/ProfileView.tsx
  shared-models/Event.ts
  shared-models/TodayOrTomorrow.ts
  shared-models/User.ts
Labels: reviews (1)

#229 Event Details: Update Events in Arrivals Tracker
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  App.tsx
  api-client/TiFAPI.ts
  api-client/client.ts
  date-time/DateRange.ts
  event-details/Event.test.ts
  event-details/Event.ts
  event-details/EventCard.test.tsx
  event-details/EventCard.tsx
  event-details/EventDetailsLoading.test.tsx
  event-details/EventDetailsLoading.tsx
  event-details/MockData.ts
  event-details/arrival-tracking/MockData.ts
  event-details/arrival-tracking/Models.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/geofencing/ExpoGeofencer.ts
  event-details/arrival-tracking/geofencing/Geofencer.ts
  event-details/arrival-tracking/geofencing/TestGeofencer.ts
  event-details/arrival-tracking/geofencing/index.ts
  event-details/arrival-tracking/index.ts
  event-details/index.ts
  lib/InternetConnection.tsx
  lib/users/User.ts
  lib/utils/Random.ts
  lib/utils/UseEffectEvent.ts
  location/search/RecentsStorage.test.ts
  location/search/SearchClient.test.ts
  screens/ExploreEvents/BottomSheet.tsx
  screens/ExploreEvents/ExploreView.tsx
  screens/ExploreEvents/Map.tsx
  screens/ExploreEvents/Navigation.tsx
  screens/ExploreEvents/models.ts
  screens/ExploreEvents/useExploreEvents.ts
  screens/ProfileScreen/EventCarousel.tsx
  screens/ProfileScreen/EventHistoryModal.tsx
  screens/ProfileScreen/ProfileView.tsx
  shared-models/Event.ts
  shared-models/TodayOrTomorrow.ts
  shared-models/User.ts
  test-helpers/AsyncStorage.ts
  test-helpers/ExpectNeverOccurs.ts
  test-helpers/InternetConnectionStatus.ts
Labels: reviews (1)

#235 Event Details: Update Event Type
  api-client/TiFAPI.ts
  event-details/EventDetailsLoading.test.tsx
  event-details/EventDetailsLoading.tsx
  event-details/MockData.ts
  shared-models/Event.ts
Labels: reviews (1)

#236 API Client: Add Optional Query Parameter Support
  api-client/client.test.ts
  api-client/client.ts
Labels: reviews (1)

#228 EAS storybook scripts & development build
  .easignore
  .env.template
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/storybook-build.yml
  .gitignore
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/.ondevice/storybook.requires.ts
  .storybook/app.config.js
  .storybook/babel.config.js
  .storybook/components/SignIn/SignIn.stories.tsx
  .storybook/components/SignUp/SignUp.stories.tsx
  .storybook/eas.json
  .storybook/metro.config.js
  .storybook/package-lock.json
  .storybook/package.json
  .storybook/tsconfig.json
  AppEntry.js
  app.config.js
  checkEnv.js
  eas.json
  easbuild.mjs
  easprebuild.mjs
  enableStorybook.js
  google-services.json
  package-lock.json
  package.json
  screens/ExploreEvents/Navigation.tsx
  setEnv.js
Labels: reviews (2)

#237 Event Details: Join Endpoint
  api-client/TiFAPI.ts
  shared-models/ChatToken.test.ts
  shared-models/ChatToken.ts
Labels: reviews (0)

#238 Event Details: Foreground Region Monitoring
  event-details/arrival-tracking/ArrivalBanner.test.tsx
  event-details/arrival-tracking/ArrivalBanner.tsx
  event-details/arrival-tracking/ArrivalsOperation.ts
  event-details/arrival-tracking/MockData.ts
  event-details/arrival-tracking/index.ts
  event-details/arrival-tracking/region-monitoring/ForegroundRegionMonitor.test.ts
  event-details/arrival-tracking/region-monitoring/ForegroundRegionMonitor.ts
  event-details/arrival-tracking/region-monitoring/RegionMonitoring.ts
  event-details/arrival-tracking/region-monitoring/index.ts
Labels: reviews (1)

#240 Region Monitoring Test Harness
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/RegionMonitoring/RegionMonitoring.stories.tsx
  package-lock.json
  package.json
Labels: reviews (3)

#241 Fix: Ensure internet connection status subscription is memoized
  lib/InternetConnection.tsx
Labels: reviews (1)

#231 New Attendees List Logic
  api-client/TiFAPI.ts
  event-details/attendees-list/AttendeesList.test.tsx
  event-details/attendees-list/AttendeesList.tsx
  event-details/attendees-list/index.ts
  lib/utils/Array.ts
  shared-models/Event.ts
  shared-models/User.ts
Labels: reviews (2)

#239 Event Details: Background Monitoring
  .storybook/.expo/README.md
  .storybook/.expo/packager-info.json
  .storybook/.expo/settings.json
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.js
  .storybook/components/RegionMonitoring/RegionMonitoring.stories.tsx
  event-details/arrival-tracking/Models.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
  event-details/arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.ts
  event-details/arrival-tracking/region-monitoring/ForegroundRegionMonitor.test.ts
  event-details/arrival-tracking/region-monitoring/ForegroundRegionMonitor.ts
  event-details/arrival-tracking/region-monitoring/RegionMonitoring.ts
  event-details/arrival-tracking/region-monitoring/RegionState.ts
  event-details/arrival-tracking/region-monitoring/TestHelpers.ts
  event-details/arrival-tracking/region-monitoring/index.ts
  package-lock.json
  package.json
Labels: reviews (1)

#248 Eslint: Remove react in scope
  .eslintrc.json
  event-details/arrival-tracking/ArrivalBanner.tsx
Labels: reviews (1)
