Repository tifapp/FitnessProject, pull requests merged in 2024-04, with the labels that each got.

#287 Explore Events: Integration
  api-client/TiFAPI.ts
  api-client/client.ts
  explore-events/ExploreEvents.test.tsx
  explore-events/ExploreEvents.tsx
Labels: reviews (0)

#292 Event Arrivals: Generic Tracker
  arrival-tracking/Arrivals.test.ts
  arrival-tracking/Arrivals.ts
  arrival-tracking/ArrivalsOperation.test.ts
  arrival-tracking/ArrivalsOperation.ts
  arrival-tracking/MockData.ts
  arrival-tracking/Models.ts
  arrival-tracking/Refresh.test.ts
  arrival-tracking/Refresh.ts
  arrival-tracking/Storage.test.ts
  arrival-tracking/Storage.ts
  arrival-tracking/TestHelpers.ts
  arrival-tracking/Tracker.test.ts
  arrival-tracking/Tracker.ts
  arrival-tracking/UpcomingArrivals.test.ts
  arrival-tracking/index.ts
  arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
  arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.ts
  event-details-boundary/JoinEvent.test.tsx
  event-details-boundary/JoinEvent.tsx
Labels: reviews (1)

#290 Sqlite: Fallback to in-memory database when opening fails
  lib/SQLite.ts
  lib/Sqlite.test.ts
  test-helpers/SQLite.ts
Labels: reviews (1)

#295 CallbackCollection Improvement
  lib/utils/CallbackCollection.ts
  settings-storage/InternalMetrics.ts
Labels: reviews (2)

#294 SQLite: Add Warn Log Message on Open Failure
  lib/SQLite.ts
Labels: reviews (1)

#293 Implement EventAttendeesList class
  event-details-boundary/MockData.ts
  event-details-boundary/attendees-list/AttendeesList.test.tsx
  event-details-boundary/attendees-list/AttendeesList.tsx
  event-details-boundary/attendees-list/EventAttendeesList.test.ts
  event-details-boundary/attendees-list/EventAttendeesList.ts
  package-lock.json
  package.json
Labels: reviews (2)

#296 Merge DeviceSettings and InternalMetrics into LocalSettings
  arrival-tracking/Refresh.test.ts
  arrival-tracking/Refresh.ts
  event-details-boundary/attendees-list/AttendeesList.tsx
  lib/SQLite.ts
  modules/tif-haptics/src/TifHapticsModule.tsx
  settings-storage/DeviceSettings.test.ts
  settings-storage/DeviceSettings.tsx
  settings-storage/Hooks.tsx
  settings-storage/InternalMetrics.test.ts
  settings-storage/InternalMetrics.ts
  settings-storage/LocalSettings.test.ts
  settings-storage/LocalSettings.ts
  test-helpers/SQLite.ts
Labels: reviews (2)

#302 Host Picker logic
  event-details-boundary/LeaveEvent.tsx
  event-details-boundary/attendees-list/HostPicker.test.tsx
  event-details-boundary/attendees-list/HostPicker.tsx
  event-details-boundary/attendees-list/Query.ts
Labels: reviews (2)
