Repository tifapp/FitnessProject, pull requests merged in 2024-07, with the labels that each got.

#344 New README
  .storybook/.ondevice/storybook.requires.ts
  README.md
  STYLEGUIDE.md
Labels: reviews (1)

#345 Edit Event: New Module
  babel.config.js
  edit-event/DurationPicker.tsx
  tsconfig.json
Labels: reviews (1)

#349 Settings: Help and Support Email Templates Language
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  lib/EmailComposition.ts
  settings-boundary/HelpAndSupport.test.tsx
  settings-boundary/HelpAndSupport.tsx
Labels: reviews (1)

#347 Event Settings Screen UI + Basic Functions
  .github/workflows/link-ticket-on-pull-request.yml
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
  .storybook/components/SettingsScreen/EventSettingsScreen.stories.tsx
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  core-root/navigation/Settings.tsx
  lib/Fonts.ts
  lib/SQLite.ts
  package-lock.json
  package.json
  settings-boundary/EventSettings.tsx
  settings-boundary/NotificationSettings.tsx
  settings-boundary/components/Button.tsx
  settings-boundary/components/NamedIconRow.tsx
  settings-boundary/components/NamedToggle.tsx
  settings-boundary/components/NavigationLink.tsx
  settings-boundary/components/ToggleCard.tsx
  settings-storage/Hooks.tsx
  settings-storage/PersistentStore.ts
  settings-storage/Settings.ts
  settings-storage/UserSettings.ts
Labels: reviews (3)

#348 Roswaal: Upload Format Update
  roswaal/Client.test.ts
  roswaal/TestCase.test.ts
  roswaal/TestCase.ts
Labels: reviews (2)
