Repository tifapp/FitnessProject, pull requests merged in 2024-10, with the labels that each got.

#393 Fix Android Build
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/tif/FitnessApp/MainActivity.kt
  android/app/src/main/java/com/tif/FitnessApp/MainApplication.kt
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/react-settings-plugin/build.gradle.kts
  android/react-settings-plugin/src/main/kotlin/expo/plugins/ReactSettingsPlugin.kt
  android/settings.gradle
  modules/tif-duration-picker/android/build.gradle
  modules/tif-duration-picker/android/src/main/AndroidManifest.xml
  modules/tif-duration-picker/android/src/main/java/expo/modules/tifdurationpicker/ExpoTiFDurationPickerModule.kt
  modules/tif-duration-picker/android/src/main/java/expo/modules/tifdurationpicker/ExpoTiFDurationPickerView.kt
  modules/tif-duration-picker/expo-module.config.json
  modules/tif-duration-picker/index.ts
  modules/tif-duration-picker/src/DurationPickerView.tsx
  package-lock.json
  package.json
  settings-boundary/EventSettings.tsx
  settings-boundary/EventSettingsDurationPicker.tsx
Labels: reviews (2)

#396 Remove Legacy lib Folders
  .storybook/components/Buttons/Buttons.stories.tsx
  lib/events/SaveEvent.ts
  lib/events/index.ts
  lib/users/User.ts
  lib/users/index.ts
Labels: reviews (1)

#394 Sync api types
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  auth-boundary/sign-up/ChangeUserHandle.tsx
  auth-boundary/sign-up/CognitoHelpers.ts
  components/profileImageComponents/ProfileImageAndName.tsx
  core-root/navigation/Settings.tsx
  core-root/navigation/auth/SignUp.test.tsx
  date-time/DateRangeFormatting.test.ts
  date-time/DateRangeFormatting.ts
  edit-event-boundary/FormValues.ts
  event-details-boundary/Details.test.tsx
  event-details-boundary/Menu.test.tsx
  event-details-boundary/Menu.tsx
  event-details-boundary/MockData.ts
  event-details-boundary/attendees-list/HostPicker.tsx
  event/ClientSideEvent.ts
  event/EventCard.tsx
  explore-events-boundary/ExploreEvents.test.tsx
  lib/SQLite.ts
  location/Recents.ts
  package-lock.json
  package.json
  settings-boundary/BlockList.test.tsx
  settings-boundary/BlockList.tsx
  settings-boundary/EventSettings.tsx
  settings-boundary/MockData.ts
  settings-storage/Settings.ts
  settings-storage/UserSettings.ts
Labels: reviews (0)

#400 Standardize Alerts
  auth-boundary/ChangePassword.tsx
  auth-boundary/VerifyCode.tsx
  auth-boundary/forgot-password/ForgotPasswordForm.test.tsx
  auth-boundary/forgot-password/ForgotPasswordForm.tsx
  auth-boundary/forgot-password/ResetPasswordForm.tsx
  auth-boundary/sign-in/SignInForm.test.tsx
  auth-boundary/sign-in/SignInForm.tsx
  auth-boundary/sign-up/ChangeUserHandle.tsx
  auth-boundary/sign-up/CredentialsForm.tsx
  content-reporting-boundary/Form.tsx
  core-root/navigation/auth/ForgotPassword.tsx
  core-root/navigation/auth/SignUp.tsx
  event-details-boundary/JoinEvent.test.tsx
  event-details-boundary/JoinEvent.tsx
  event-details-boundary/LeaveEvent.test.tsx
  event-details-boundary/LeaveEvent.tsx
  event-details-boundary/attendees-list/HostPicker.test.tsx
  event-details-boundary/attendees-list/HostPicker.tsx
  lib/Alerts.ts
  package-lock.json
  package.json
  settings-boundary/AccountInfo.test.tsx
  settings-boundary/AccountInfo.tsx
  settings-boundary/BlockList.test.tsx
  settings-boundary/BlockList.tsx
  settings-boundary/HelpAndSupport.test.tsx
  settings-boundary/HelpAndSupport.tsx
  test-helpers/Alerts.ts
  test-helpers/Matchers.ts
Labels: reviews (1)

#408 Better Primary Button
  .storybook/components/Buttons/Buttons.stories.tsx
  .storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
  auth-boundary/AuthLayout.tsx
  components/Buttons.tsx
  content-reporting-boundary/Success.tsx
  explore-events-boundary/ExploreEvents.tsx
Labels: reviews (0)

#406 Edit Event: Host Map Marker
  .storybook/components/EditEvent/PragmaQuote.stories.tsx
  edit-event-boundary/EditEvent.tsx
  edit-event-boundary/Location.tsx
Labels: reviews (0)

#405 Blue Tinted Colors
  .storybook/components/EditEvent/PragmaQuote.stories.tsx
  auth-boundary/ChangePassword.tsx
  auth-boundary/forgot-password/ForgotPasswordForm.tsx
  components/BottomSheet.tsx
  components/Buttons.tsx
  components/Text.tsx
  components/TextFields.tsx
  components/common/ConfirmationDialogue.tsx
  components/common/Icons.tsx
  components/common/Toasts.tsx
  components/form-components/Card.tsx
  components/form-components/PreviewableOption.tsx
  components/form-components/Switch.tsx
  components/form-components/ToggleCard.tsx
  core-root/navigation/TabBar.tsx
  edit-event-boundary/DurationPicker.tsx
  edit-event-boundary/EditEvent.tsx
  edit-event-boundary/Location.tsx
  edit-event-boundary/PragmaQuotes.tsx
  event-details-boundary/ArrivalBanner.tsx
  event-details-boundary/Countdown.tsx
  event-details-boundary/Details.tsx
  event-details-boundary/TravelEstimates.tsx
  lib/AppColorStyle.ts
  location-search-boundary/SearchResultView.tsx
  modules/tif-duration-picker/src/DurationPickerView.tsx
  settings-boundary/AccountInfo.tsx
  settings-boundary/AppearanceSettings.tsx
  settings-boundary/EventSettings.tsx
  settings-boundary/HelpAndSupport.tsx
  settings-boundary/PrivacySettings.tsx
  settings-boundary/RootSettings.tsx
Labels: reviews (1)

#398 Tifapi integration
  .github/workflows/build.yml
  .storybook/components/SignIn/SignIn.stories.tsx
  arrival-tracking/ArrivalsOperation.test.ts
  arrival-tracking/ArrivalsOperation.ts
  arrival-tracking/Refresh.test.ts
  auth-boundary/sign-up/Environment.test.ts
  auth-boundary/sign-up/Environment.ts
  core-root/navigation/auth/SignUp.test.tsx
  event-details-boundary/Details.test.tsx
  event-details-boundary/Details.tsx
  event-details-boundary/JoinEvent.test.tsx
  event-details-boundary/JoinEvent.tsx
  explore-events-boundary/ExploreEvents.test.tsx
  explore-events-boundary/ExploreEvents.tsx
  lib/TiFAPI.ts
  notifications/RegisterForPushNotifications.test.ts
  notifications/RegisterForPushNotifications.ts
  package-lock.json
  package.json
  settings-storage/UserSettings.test.ts
  settings-storage/UserSettings.ts
  test-helpers/msw.ts
Labels: reviews (2)

#409 Common Footer View
  .storybook/components/EditEvent/PragmaQuote.stories.tsx
  auth-boundary/AuthLayout.tsx
  components/Footer.tsx
  components/form-components/ScrollView.tsx
  components/form-components/ScrollableFormLayout.tsx
  edit-event-boundary/EditEvent.tsx
Labels: reviews (1)

#407 Fix CI Node Version
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .storybook/components/Buttons/Buttons.stories.tsx
  .storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
  auth-boundary/AuthLayout.tsx
  components/Buttons.tsx
  content-reporting-boundary/Success.tsx
  explore-events-boundary/ExploreEvents.tsx
Labels: reviews (0)

#404 Edit Event: Form Location
  .storybook/components/Buttons/Buttons.stories.tsx
  .storybook/components/EditEvent/PragmaQuote.stories.tsx
  .storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
  auth-boundary/AuthLayout.tsx
  auth-boundary/ChangePassword.tsx
  auth-boundary/forgot-password/ForgotPasswordForm.tsx
  components/BottomSheet.tsx
  components/Buttons.tsx
  components/Footer.tsx
  components/Text.tsx
  components/TextFields.tsx
  components/common/ConfirmationDialogue.tsx
  components/common/Icons.tsx
  components/common/Toasts.tsx
  components/form-components/Card.tsx
  components/form-components/Label.tsx
  components/form-components/NamedIconRow.tsx
  components/form-components/NavigationLink.tsx
  components/form-components/PreviewableOption.tsx
  components/form-components/RowItem.tsx
  components/form-components/ScrollView.tsx
  components/form-components/ScrollableFormLayout.tsx
  components/form-components/Section.tsx
  components/form-components/Switch.tsx
  components/form-components/ToggleCard.tsx
  content-reporting-boundary/Success.tsx
  core-root/navigation/TabBar.tsx
  date-time/DateRangeFormatting.ts
  edit-event-boundary/DurationPicker.tsx
  edit-event-boundary/EditEvent.tsx
  edit-event-boundary/Location.test.tsx
  edit-event-boundary/Location.tsx
  edit-event-boundary/PragmaQuotes.tsx
  edit-event-boundary/Submit.tsx
  event-details-boundary/ArrivalBanner.tsx
  event-details-boundary/Countdown.tsx
  event-details-boundary/Details.tsx
  event-details-boundary/TravelEstimates.tsx
  explore-events-boundary/ExploreEvents.tsx
  lib/AppColorStyle.ts
  location-search-boundary/SearchResultView.tsx
  location/Geocoding.tsx
  modules/tif-duration-picker/src/DurationPickerView.tsx
  package-lock.json
  package.json
  settings-boundary/AccountInfo.tsx
  settings-boundary/AppearanceSettings.tsx
  settings-boundary/EventSettings.tsx
  settings-boundary/HelpAndSupport.tsx
  settings-boundary/PrivacySettings.tsx
  settings-boundary/RootSettings.tsx
Labels: reviews (1)

#410 Fix iOS Duration Picker
  modules/tif-duration-picker/src/DurationPickerView.tsx
Labels: reviews (1)

#415 Fix Android Maps API Key
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  app.config.js
  injectGradleSecretsPlugin.js
Labels: reviews (1)

#417 Haptics: Storybook
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/Haptics/Haptics.stories.tsx
Labels: reviews (1)
