Repository tifapp/FitnessProject, pull requests merged in 2024-08, with the labels that each got.

#370 Remove Unnecessary Acceptance Tests
  roswaal/basic-join-event-through-exploration/TestActions.ts
  roswaal/basic-join-event-through-exploration/TestCase.test.ts
  roswaal/basic-leave-event-through-exploration-as-attendee/TestActions.ts
  roswaal/basic-leave-event-through-exploration-as-attendee/TestCase.test.ts
Labels: reviews (1)

#369 Added github action for roswaal branch endpoints
  .github/workflows/roswaal-bot.yml
Labels: reviews (0)

#371 IGNORE_BUILD: Conditionally pass build step
  .github/workflows/auto-pass.yml
  .github/workflows/build.yml
Labels: reviews (1)

#372 Use dummy password for debugging
  .github/workflows/auto-pass.yml
  .github/workflows/roswaal-bot.yml
Labels: reviews (0)

#374 use single quotes in curl command
  .github/workflows/roswaal-bot.yml
Labels: reviews (0)

#365 Edit Event: Pragma Quotes
  edit-event/PragmaQuotes.test.ts
  edit-event/PragmaQuotes.ts
Labels: reviews (2)

#376 only send curl commands if branch starts with roswaal
  .github/workflows/roswaal-bot.yml
Labels: reviews (1)

#377 Compile Logs
  .gitignore
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  App.tsx
  ios/Podfile.lock
  lib/Logging.ts
  modules/tif-fs/android/build.gradle
  modules/tif-fs/android/src/main/AndroidManifest.xml
  modules/tif-fs/android/src/main/java/expo/modules/tiffs/ExpoTiFFileSystemModule.kt
  modules/tif-fs/expo-module.config.json
  modules/tif-fs/index.ts
  modules/tif-fs/ios/ExpoTiFFileSystem.podspec
  modules/tif-fs/ios/ExpoTiFFileSystemModule.swift
  modules/tif-fs/src/ExpoTiFFileSystemModule.ts
Labels: reviews (1)

#378 Event Arrivals: Unconditionally Subscribe to Geofencer
  arrival-tracking/Tracker.test.ts
  arrival-tracking/Tracker.ts
  arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
Labels: reviews (1)

#382 Event Arrivals: Deduplicate Arrival Operations
  arrival-tracking/Storage.test.ts
  arrival-tracking/Storage.ts
  arrival-tracking/Tracker.test.ts
  arrival-tracking/Tracker.ts
Labels: reviews (0)

#380 Bundle Identifier adjustment
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/tifapp/FitnessApp/MainActivity.kt
  android/app/src/main/java/com/tifapp/FitnessApp/MainApplication.kt
  app.config.js
  ios/FitnessApp.xcodeproj/project.pbxproj
  ios/FitnessApp/Info.plist
Labels: reviews (0)

#383 Event Settings Duration Picker - Javascript
  .storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
  .storybook/components/SignIn/SignIn.stories.tsx
  settings-boundary/EventSettings.tsx
  settings-boundary/EventSettingsDurationPicker.tsx
  settings-boundary/components/ScrollView.tsx
Labels: reviews (1)
