Repository tifapp/FitnessProject, pull requests merged in 2024-12, with the labels that each got.

#423 Friend Request: Generic Friend Request View
  event-details-boundary/Details.tsx
  lib/utils/Form.ts
  user/FriendRequest.test.tsx
  user/FriendRequest.tsx
Labels: reviews (0)

#424 Avatar Functionality
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/ProfileScreen/Avatar.stories.tsx
  .storybook/components/RudeusEditor/RudeusAPI.ts
  components/Avatar.test.tsx
  components/Avatar.tsx
  modules/tif-haptics/src/TifHapticsModule.tsx
  package-lock.json
  package.json
Labels: reviews (0)

#425 Event Details: Alpha Attendees List
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  components/Avatar.tsx
  components/Buttons.tsx
  components/Text.tsx
  components/common/Toasts.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  event-details-boundary/AttendeesList.test.tsx
  event-details-boundary/AttendeesList.tsx
  event-details-boundary/Details.tsx
  event-details-boundary/MockData.ts
  event-details-boundary/attendees-list/AttendeesList.test.tsx
  event-details-boundary/attendees-list/AttendeesList.tsx
  event-details-boundary/attendees-list/EventAttendeesList.test.ts
  event-details-boundary/attendees-list/EventAttendeesList.ts
  event-details-boundary/attendees-list/HostPicker.test.tsx
  event-details-boundary/attendees-list/HostPicker.tsx
  event-details-boundary/attendees-list/Query.ts
  event-details-boundary/attendees-list/index.ts
  event/ClientSideEvent.ts
  ios/FitnessApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
  lib/AppColorStyle.ts
  lib/utils/Form.ts
  user/FriendRequest.tsx
Labels: reviews (1)

#426 Event Details: Join + Leave Event Update
  .storybook/components/EventDetails/EventDetails.stories.tsx
  event-details-boundary/LeaveEvent.tsx
  event-details-boundary/TravelEstimates.tsx
  event-details-boundary/index.ts
  event/JoinEvent.test.tsx
  event/JoinEvent.tsx
  event/LeaveEvent.test.tsx
  event/LeaveEvent.tsx
  event/LocationIdentifier.test.ts
  event/LocationIdentifier.ts
  event/UserAttendance.tsx
Labels: reviews (2)

#430 Name entry story
  .storybook/.ondevice/Storybook.tsx
  components/NameEntry/NameEntry.stories.tsx
  core-root/NameEntry.tsx
Labels: reviews (1)

#431 Event Card Update
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/EventDetails/EventDetails.stories.tsx
  components/Avatar.tsx
  components/CalendarDay.tsx
  components/profileImageComponents/ProfileCircle.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  event/EventCard.test.tsx
  event/EventCard.tsx
  event/JoinEvent.tsx
  event/LeaveEvent.tsx
  event/Menu.tsx
  event/UserAttendance.tsx
Labels: reviews (1)

#433 Alpha Registration Helper
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  .storybook/components/NameEntry/NameEntry.stories.tsx
  core-root/AlphaRegister.test.tsx
  core-root/AlphaRegister.tsx
  user/Session.tsx
  user/alpha/AlphaUser.tsx
Labels: reviews (1)

#429 Create Story script
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/NameEntry/NameEntry.stories.tsx
  create-story.ts
  package.json
Labels: reviews (0)

#427 Event Details: Menu Actions Update
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/App.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  .storybook/components/NameEntry/NameEntry.stories.tsx
  .storybook/components/SignIn/SignIn.stories.tsx
  .storybook/components/SignUp/SignUp.stories.tsx
  App.tsx
  api/TiFAPI.test.ts
  api/TiFAPI.ts
  api/index.ts
  babel.config.js
  components/Avatar.tsx
  components/CalendarDay.tsx
  components/profileImageComponents/ProfileCircle.tsx
  components/profileImageComponents/ProfileImageAndName.tsx
  core-root/AlphaRegister.test.tsx
  core-root/AlphaRegister.tsx
  event/EventCard.test.tsx
  event/EventCard.tsx
  event/JoinEvent.tsx
  event/LeaveEvent.tsx
  event/Menu.test.tsx
  event/Menu.tsx
  event/UserAttendance.tsx
  tsconfig.json
  user/Blocking.tsx
  user/Session.tsx
  user/alpha/AlphaUser.test.ts
  user/alpha/AlphaUser.tsx
  user/alpha/MockData.ts
  user/alpha/index.ts
  user/privacy/EmailAddress.ts
Labels: reviews (0)

#436 New Profile Screen Component
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/ProfileScreen/Avatar.stories.tsx
  AppEntry.js
  event/EventCard.tsx
  modules/tif-haptics/android/build.gradle
  package-lock.json
  package.json
  user-profile-boundary/UpcomingEvents.test.tsx
  user-profile-boundary/UpcomingEvents.tsx
  user-profile-boundary/UserProfile.test.tsx
  user-profile-boundary/UserProfile.tsx
  user-profile-boundary/index.tsx
  user/FriendRequest.tsx
  user/alpha/AlphaUser.tsx
Labels: reviews (0)
