Repository tifapp/FitnessProject, pull requests merged in 2024-03, with the labels that each got.

#265 Event Details: Join Event Logic + Cleanup
  .storybook/components/EventDetails/EventDetails.stories.tsx
  api-client/TiFAPI.ts
  event-details/JoinEvent.test.tsx
  event-details/JoinEvent.tsx
  event-details/MockData.ts
  event-details/arrival-tracking/Tracker.ts
  lib/SQLite.ts
  location/search/RecentsStorage.ts
  location/search/SearchResultView.tsx
  shared-models/EventArrivals.ts
  shared-models/JoinEvent.ts
Labels: reviews (1)

#264 Allow dashed object keys
  .eslintrc.json
Labels: reviews (0)

#271 Navigation Relocation
  .storybook/components/ContentReporting/ContentReporting.stories.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  .storybook/components/Explore/Explore.stories.tsx
  .storybook/components/ForgotPassword/ForgotPasswordForm.stories.tsx
  .storybook/components/SignIn/SignIn.stories.tsx
  .storybook/components/SignUp/SignUp.stories.tsx
  auth/forgot-password/index.ts
  auth/sign-in/index.ts
  auth/sign-up/index.ts
  content-reporting/index.ts
  root-feature/AppView.tsx
  root-feature/navigation/ContentReporting.tsx
  root-feature/navigation/ExploreEvents.tsx
  root-feature/navigation/LinkingConfig.test.ts
  root-feature/navigation/LinkingConfig.ts
  root-feature/navigation/TabBar.tsx
  root-feature/navigation/auth/ForgotPassword.test.tsx
  root-feature/navigation/auth/ForgotPassword.tsx
  root-feature/navigation/auth/SignIn.test.tsx
  root-feature/navigation/auth/SignIn.tsx
  root-feature/navigation/auth/SignUp.test.tsx
  root-feature/navigation/auth/SignUp.tsx
  root-feature/navigation/auth/Stack.tsx
  root-feature/navigation/auth/index.ts
  root-feature/navigation/index.ts
  screens/ExploreEvents/index.ts
Labels: reviews (1)

#269 React Query Refetching
  App.tsx
  event-details/Details.test.tsx
  event-details/Details.tsx
  lib/InternetConnection.tsx
  lib/ReactQuery.tsx
Labels: reviews (1)

#270 Update Dependencies
  .storybook/.ondevice/Storybook.tsx
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/tifapp/FitnessApp/MainActivity.kt
  android/app/src/main/java/com/tifapp/FitnessApp/MainApplication.kt
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/gradle.properties
  ios/FitnessApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: reviews (0)

#268 Event Details: Countdown
  .storybook/components/EventDetails/EventDetails.stories.tsx
  App.tsx
  components/Buttons.tsx
  components/Text.tsx
  date-time/DateRange.ts
  event-details/Countdown.test.tsx
  event-details/Countdown.tsx
  event-details/Details.test.tsx
  event-details/Details.tsx
  event-details/Event.ts
  event-details/JoinEvent.tsx
  event-details/arrival-tracking/ArrivalBanner.tsx
  lib/AutocorrectingInterval.test.ts
  lib/AutocorrectingInterval.ts
  lib/InternetConnection.tsx
  lib/ReactQuery.tsx
  lib/utils/Color.ts
  lib/utils/Math.test.ts
  lib/utils/Math.ts
  lib/utils/String.ts
  lib/utils/UseInterval.ts
  test-helpers/Timers.ts
Labels: reviews (2)

#272 Event Details: Update Response
  event-details/Details.test.tsx
  event-details/MockData.ts
  shared-models/Event.ts
Labels: reviews (2)

#275 Event Details: Shared Countdown
  .storybook/components/EventDetails/EventDetails.stories.tsx
  event-details/Countdown.test.tsx
  event-details/Countdown.tsx
  event-details/SecondsToStart.test.tsx
  event-details/SecondsToStart.ts
  event-details/arrival-tracking/ArrivalBanner.test.tsx
  event-details/arrival-tracking/ArrivalBanner.tsx
Labels: reviews (1)

#273 Event Details: Misc/Menu Actions
  .storybook/components/EventDetails/EventDetails.stories.tsx
  android/app/build.gradle
  android/app/src/main/java/com/tifapp/FitnessApp/MainActivity.kt
  android/app/src/main/java/com/tifapp/FitnessApp/MainApplication.kt
  event-details/Menu.test.ts
  event-details/Menu.tsx
Labels: reviews (1)

#276 Event Details: Replace Edit Menu Action with Block Toggling
  .storybook/components/EventDetails/EventDetails.stories.tsx
  event-details/Menu.test.ts
  event-details/Menu.tsx
Labels: reviews (2)

#274 Auth Banner UI
  .storybook/components/Buttons/Buttons.stories.tsx
  auth/session/AuthBanner.test.tsx
  auth/session/AuthBanner.tsx
  auth/session/index.ts
  components/AuthBanner.tsx
  components/common/Icons.tsx
  lib/UserSession.test.tsx
  lib/UserSession.tsx
Labels: reviews (1)

#277 Shared Query Keys Folder
  event-details/Details.tsx
  event-details/Query.ts
  screens/ExploreEvents/useExploreEvents.ts
  shared-models/Event.ts
  shared-models/User.ts
  shared-models/query-keys/Event.ts
  tests/events/ExploreEvents.test.tsx
Labels: reviews (1)

#279 Fix eas build action
  .github/workflows/deploy.yml
Labels: reviews (0)

#278 API: Block and Unblock
  api-client/TiFAPI.ts
Labels: reviews (1)

#280 Event Details: Use Menu Actions
  .storybook/components/EventDetails/EventDetails.stories.tsx
  event-details/Details.test.tsx
  event-details/Menu.test.ts
  event-details/Menu.test.tsx
  event-details/Menu.tsx
  event-details/Query.ts
  event-details/TestHelpers.tsx
  lib/UserSession.tsx
  shared-models/User.ts
  test-helpers/InternetConnectionStatus.ts
Labels: reviews (1)

#282 Event Details: Update Query Client on successful join
  event-details/JoinEvent.test.tsx
  event-details/JoinEvent.tsx
  event-details/Menu.test.tsx
  event-details/TestHelpers.tsx
Labels: reviews (0)

#267 Leave Event Logic
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  event-details/LeaveEvent.test.tsx
  event-details/LeaveEvent.tsx
  event-details/Menu.test.tsx
  event-details/attendees-list/AttendeesList.test.tsx
  event-details/attendees-list/AttendeesList.tsx
  package-lock.json
  package.json
Labels: reviews (1)

#285 Get events by region endpoint
  api-client/TiFAPI.ts
Labels: reviews (1)

#286 Explore Events: Modernization
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/Explore/Explore.stories.tsx
  babel.config.js
  explore-events/BottomSheet.tsx
  explore-events/ExploreEvents.test.tsx
  explore-events/ExploreEvents.tsx
  explore-events/Map.tsx
  explore-events/MapMarker.tsx
  explore-events/Models.test.ts
  explore-events/Models.ts
  explore-events/SearchBar.tsx
  explore-events/SkeletonEventCard.tsx
  explore-events/index.ts
  lib/Cancellable.ts
  package-lock.json
  package.json
  root-feature/navigation/ExploreEvents.tsx
  screens/ExploreEvents/index.ts
  screens/ExploreEvents/useExploreEvents.ts
  test-helpers/Cancellable.ts
  tsconfig.json
Labels: reviews (0)
