Repository tifapp/FitnessProject, pull requests merged in 2024-06, with the labels that each got.

#333 Async Image Loading
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  components/profileImageComponents/ProfileImage.tsx
  ios/Podfile.lock
  package-lock.json
  package.json
  settings-boundary/BlockList.tsx
  settings-boundary/MockData.ts
Labels: reviews (0)

#337 Clear Legacy Code/Files/Folders
  .storybook/HelperTypes.ts
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  .storybook/components/ChangePassword/ChangePassword.stories.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  .storybook/components/ForgotPassword/ForgotPasswordForm.stories.tsx
  .storybook/components/LocationSearch/LocationSearch.stories.tsx
  .storybook/components/RegionMonitoring/RegionMonitoring.stories.tsx
  .storybook/components/SearchBar/SearchBar.stories.tsx
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  .storybook/components/SignIn/SignIn.stories.tsx
  .storybook/components/SignUp/SignUp.stories.tsx
  .storybook/components/VerificationCode/VerifyCode.stories.tsx
  App.tsx
  androidtimerfix.js
  babel.config.js
  components/SearchBar.test.tsx
  components/eventForm/EventFormScreen.test.tsx
  components/eventForm/EventFormScreen.tsx
  components/eventForm/LocationBanner.test.tsx
  components/eventForm/TestHelpers.ts
  components/formComponents/HexColorPicker.test.tsx
  core-root/navigation/TabBar.tsx
  global.d.ts
  screens/EventDetailsScreenNavWrapper.tsx
  screens/EventFormScreenNavWrapper.tsx
  screens/ProfileScreen/EditProfileScreen/EditProfileView.tsx
  screens/ProfileScreen/EventCarousel.tsx
  screens/ProfileScreen/EventHistoryModal.tsx
  screens/ProfileScreen/Navigation/EditProfileDismissButton.tsx
  screens/ProfileScreen/Navigation/ProfileHeaders.tsx
  screens/ProfileScreen/Navigation/ProfileScreensNavigation.tsx
  screens/ProfileScreen/Navigation/SignInScreensNavigation.tsx
  screens/ProfileScreen/ProfileView.tsx
  screens/ProfileScreen/state.ts
  screens/SettingsScreen/PrivacyPolicy.tsx
  screens/SettingsScreen/Section.tsx
  screens/SettingsScreen/SettingsScreen.tsx
  tsconfig.json
Labels: reviews (1)

#336 Roswaal: Test Progress Monitoring
  jest.config.js
  native-code/iOS/TiFNative/.swiftpm/xcode/package.xcworkspace/xcuserdata/matthewhayes.xcuserdatad/UserInterfaceState.xcuserstate
  native-code/iOS/TiFNative/.swiftpm/xcode/xcuserdata/matthewhayes.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  native-code/iOS/TiFNative/.swiftpm/xcode/xcuserdata/matthewhayes.xcuserdatad/xcschemes/xcschememanagement.plist
  package.json
  roswaal/Client.test.ts
  roswaal/Client.ts
  roswaal/Teardown.js
  roswaal/TestCase.test.ts
  roswaal/TestCase.ts
  roswaal/jest.config.js
  roswaal/jest.infra.config.js
Labels: reviews (0)

#330 Settings: Calendar Settings + Update Components
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  settings-boundary/AppearanceSettings.tsx
  settings-boundary/CalendarSettings.tsx
  settings-boundary/components/Label.tsx
  settings-boundary/components/MenuPicker.tsx
  settings-boundary/components/NamedToggle.tsx
  settings-boundary/components/PreviewableOption.tsx
  settings-boundary/components/RowItem.tsx
  settings-boundary/index.ts
Labels: reviews (1)

#335 Open Weblink Functionallity
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  android/app/build.gradle
  components/ContentText.test.tsx
  components/ContentText.tsx
  ios/Podfile.lock
  modules/tif-weblinks/android/.gradle/7.5.1/checksums/checksums.lock
  modules/tif-weblinks/android/.gradle/7.5.1/dependencies-accessors/dependencies-accessors.lock
  modules/tif-weblinks/android/.gradle/7.5.1/dependencies-accessors/gc.properties
  modules/tif-weblinks/android/.gradle/7.5.1/fileChanges/last-build.bin
  modules/tif-weblinks/android/.gradle/7.5.1/fileHashes/fileHashes.lock
  modules/tif-weblinks/android/.gradle/7.5.1/gc.properties
  modules/tif-weblinks/android/.gradle/8.3/checksums/checksums.lock
  modules/tif-weblinks/android/.gradle/8.3/dependencies-accessors/dependencies-accessors.lock
  modules/tif-weblinks/android/.gradle/8.3/dependencies-accessors/gc.properties
  modules/tif-weblinks/android/.gradle/8.3/fileChanges/last-build.bin
  modules/tif-weblinks/android/.gradle/8.3/fileHashes/fileHashes.lock
  modules/tif-weblinks/android/.gradle/8.3/gc.properties
  modules/tif-weblinks/android/.gradle/vcs-1/gc.properties
  modules/tif-weblinks/android/build.gradle
  modules/tif-weblinks/android/src/main/AndroidManifest.xml
  modules/tif-weblinks/android/src/main/java/expo/modules/tifweblinks/ExpoTiFWeblinksModule.kt
  modules/tif-weblinks/expo-module.config.json
  modules/tif-weblinks/index.ts
  modules/tif-weblinks/ios/ExpoTiFWeblinks.podspec
  modules/tif-weblinks/ios/ExpoTiFWeblinksModule.swift
  modules/tif-weblinks/src/ExpoTiFWeblinksModule.tsx
  native-code/iOS/TiFNative/Sources/TiFNative/Weblinks/UIApplication+OpenWeblink.swift
  settings-boundary/AppearanceSettings.tsx
  settings-storage/PersistentStore.ts
Labels: reviews (0)

#338 Fix EAS Build: Move TiFShared import to root + point TiFShared version to main branch
  .storybook/App.tsx
  App.tsx
  AppEntry.js
  package-lock.json
  package.json
  types/env.d.ts
Labels: reviews (0)

#288 Send QR codes to latest-build channel instead of eng-general.
  easbuild.mjs
Labels: reviews (0)

#340 Settings: Update Language
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  settings-boundary/AccountInfo.tsx
  settings-boundary/BlockList.tsx
  settings-boundary/NotificationSettings.tsx
Labels: reviews (0)

#339 Add watchmanconfig to try and improve expo startup time
  .watchmanconfig
Labels: reviews (2)

#341 Settings: Open Dyslexic iOS 18 Alignment Fix
  lib/Platform.ts
  settings-boundary/AppearanceSettings.tsx
Labels: reviews (1)

#342 Mail Composer Wrapper
  lib/EmailComposition.ts
  package-lock.json
  package.json
Labels: reviews (1)

#343 Help and support screen
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/SettingsScreen/SettingsScreen.stories.tsx
  components/ContentText.tsx
  package-lock.json
  package.json
  settings-boundary/HelpAndSupport.test.tsx
  settings-boundary/HelpAndSupport.tsx
  settings-boundary/components/NavigationLink.tsx
Labels: reviews (2)
