Repository tifapp/FitnessProject, pull requests merged in 2024-11, with the labels that each got.

#420 eas update
  package-lock.json
  package.json
Labels: reviews (1)

#412 Root View: Footer + Home Screen Paging
  .github/workflows/build.yml
  .gitignore
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/TiFPreview/TiFPreview.stories.tsx
  App.tsx
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  app.config.js
  components/Footer.tsx
  components/Pager.tsx
  components/common/Icons.tsx
  core-root/AppView.tsx
  core-root/Context.tsx
  core-root/Home.tsx
  core-root/TiFView.tsx
  core-root/index.ts
  explore-events-boundary/ExploreEvents.test.tsx
  explore-events-boundary/ExploreEvents.tsx
  injectGradleSecretsPlugin.js
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: reviews (2)

#416 Haptics: AHAP JS Representation
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/assets/celebrate.wav
  .storybook/components/Haptics/Haptics.stories.tsx
  ios/Podfile.lock
  modules/tif-haptics/ios/TifHaptics.podspec
  modules/tif-haptics/ios/TifHaptics.swift
  modules/tif-haptics/ios/TifHapticsModule.swift
  modules/tif-haptics/src/TifHapticsModule.test.ts
  modules/tif-haptics/src/TifHapticsModule.tsx
  native-code/iOS/TiFNative/.swiftpm/xcode/package.xcworkspace/xcuserdata/matthewhayes.xcuserdatad/UserInterfaceState.xcuserstate
  native-code/iOS/TiFNative/Sources/TiFNative/CancellableCompletionRequest.swift
  native-code/iOS/TiFNative/Sources/TiFNative/Haptics/CHHapticPattern+ExpoObject.swift
  native-code/iOS/TiFNative/Sources/TiFNative/Haptics/HapticsSettings.swift
  native-code/iOS/TiFNative/Sources/TiFNative/Haptics/TiFHapticsEngine.swift
  native-code/iOS/TiFNative/Sources/TiFNative/TravelEstimates/MKDirections+Extensions.swift
  native-code/iOS/TiFNative/Tests/TiFNativeTests/CHHapticPattern+ExpoObjectTests.swift
Labels: reviews (3)

#419 Rudeus: Haptic Editor
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/Haptics/Haptics.stories.tsx
  .storybook/components/RudeusEditor/Models.test.ts
  .storybook/components/RudeusEditor/Models.ts
  .storybook/components/RudeusEditor/PatternEditor.test.tsx
  .storybook/components/RudeusEditor/PatternEditor.tsx
  .storybook/components/RudeusEditor/PatternElementEditor.test.tsx
  .storybook/components/RudeusEditor/PatternElementEditor.tsx
  .storybook/components/RudeusEditor/Patterns.tsx
  .storybook/components/RudeusEditor/PreviewElementPattern.test.ts
  .storybook/components/RudeusEditor/PreviewElementPattern.ts
  .storybook/components/RudeusEditor/README.md
  .storybook/components/RudeusEditor/Register.test.tsx
  .storybook/components/RudeusEditor/Register.tsx
  .storybook/components/RudeusEditor/Rudeus.tsx
  .storybook/components/RudeusEditor/RudeusAPI.ts
  .storybook/components/RudeusEditor/RudeusEditor.stories.tsx
  .storybook/components/RudeusEditor/Stepper.test.tsx
  .storybook/components/RudeusEditor/Stepper.tsx
  .storybook/components/RudeusEditor/TestHelpers.ts
  .storybook/components/RudeusEditor/UserStorage.ts
  app.config.js
  auth-boundary/CognitoSecureStorage.test.ts
  auth-boundary/CognitoSecureStorage.ts
  bundled-sound-effects/appear.mp3
  bundled-sound-effects/debris.mp3
  bundled-sound-effects/fall.mp3
  components/form-components/RowItem.tsx
  components/form-components/ScrollableFormLayout.tsx
  injectBundledSoundEffects.js
  ios/FitnessApp.xcodeproj/project.pbxproj
  ios/FitnessApp/appear.caf
  ios/FitnessApp/debris.caf
  ios/FitnessApp/fall.caf
  lib/Jotai.ts
  lib/SecureStore.ts
  lib/SoundEffect.ts
  lib/TiFAPI.ts
  lib/utils/UseRefreshOnFocus.ts
  modules/tif-haptics/src/TifHapticsModule.test.ts
  modules/tif-haptics/src/TifHapticsModule.tsx
  package-lock.json
  package.json
  test-helpers/Haptics.ts
  types/env.d.ts
Labels: reviews (0)

#422 API: Update Endpoint Calls
  arrival-tracking/ArrivalsOperation.test.ts
  arrival-tracking/ArrivalsOperation.ts
  auth-boundary/sign-up/Environment.test.ts
  auth-boundary/sign-up/Environment.ts
  core-root/navigation/auth/SignUp.test.tsx
  edit-event-boundary/EditEvent.tsx
  edit-event-boundary/FormValues.ts
  edit-event-boundary/Submit.test.tsx
  edit-event-boundary/Submit.tsx
  event-details-boundary/Details.test.tsx
  event-details-boundary/MockData.ts
  explore-events-boundary/ExploreEvents.test.tsx
  jest/setup.js
  package-lock.json
  package.json
Labels: reviews (1)
