Repository tifapp/FitnessProject, pull requests merged in 2024-09, with the labels that each got.

#350 Event Settings Duration Picker - Edit Mode
  .storybook/components/SettingsScreen/EventSettingsDurations.stories.tsx
  settings-boundary/EventSettings.tsx
Labels: reviews (0)

#385 Edit Event: Rename to Boundary Module
  .storybook/components/EditEvent/DurationPicker.stories.tsx
  babel.config.js
  edit-event-boundary/DurationPicker.test.ts
  edit-event-boundary/DurationPicker.tsx
  edit-event-boundary/PragmaQuotes.test.ts
  edit-event-boundary/PragmaQuotes.ts
  tsconfig.json
Labels: reviews (1)

#384 Edit Event: Durations Slider
  .storybook/.ondevice/Storybook.tsx
  .storybook/components/EditEvent/DurationPicker.stories.tsx
  babel.config.js
  edit-event-boundary/DurationPicker.test.ts
  edit-event-boundary/DurationPicker.tsx
  edit-event-boundary/PragmaQuotes.test.ts
  edit-event-boundary/PragmaQuotes.ts
  edit-event/DurationPicker.tsx
  lib/Fonts.ts
  lib/Reanimated.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: reviews (2)

#389 Make project build with Xcode 16
  app.config.js
  injectTiFNativePod.js
  ios/FitnessApp.xcodeproj/project.pbxproj
  ios/FitnessApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/FitnessApp/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
Labels: reviews (0)

#388 Remove Many Legacy Components
  .storybook/components/SearchBar/SearchBar.stories.tsx
  components/Divider.tsx
  components/ProfileImagePicker.tsx
  components/bottomTabComponents/AttendanceButton.tsx
  components/bottomTabComponents/BottomTabButton.tsx
  components/common/CustomizableTextInput.tsx.tsx
  components/common/ExpandableText.tsx
  components/common/IconButton.tsx
  components/common/Icons.tsx
  components/eventForm/AdvancedSettings.tsx
  components/eventForm/BottomSheet.tsx
  components/eventForm/ColorPicker.tsx
  components/eventForm/DatePicker.tsx
  components/eventForm/DismissButton.tsx
  components/eventForm/EventForm.tsx
  components/eventForm/EventFormScreen.test.tsx
  components/eventForm/EventFormScreen.tsx
  components/eventForm/EventFormValues.ts
  components/eventForm/LocationBanner.test.tsx
  components/eventForm/LocationBanner.tsx
  components/eventForm/SectionHeader.tsx
  components/eventForm/SubmitButton.tsx
  components/eventForm/TestHelpers.ts
  components/eventForm/TextField.tsx
  components/eventForm/Toolbar.tsx
  components/eventForm/index.tsx
  components/formComponents/FormLabels.tsx
  components/formComponents/HexColorPicker.test.tsx
  components/formComponents/HexColorPicker.tsx
  components/profileImageComponents/ProfileImageAndNameWithFriend.tsx
  date-time/DateTimePicker.test.tsx
  date-time/DateTimePicker.tsx
Labels: reviews (0)

#386 Edit Event: Form Values
  edit-event-boundary/FormValues.test.ts
  edit-event-boundary/FormValues.ts
  edit-event-boundary/PragmaQuotes.ts
  lib/Jotai.ts
  package-lock.json
  package.json
Labels: reviews (0)

#387 Settings Components -> Generic Form Components
  components/form-components/Button.tsx
  components/form-components/Card.tsx
  components/form-components/ChecklistPicker.tsx
  components/form-components/Label.tsx
  components/form-components/MenuPicker.tsx
  components/form-components/NamedIconRow.tsx
  components/form-components/NamedToggle.tsx
  components/form-components/NavigationLink.tsx
  components/form-components/PreviewableOption.tsx
  components/form-components/RowItem.tsx
  components/form-components/ScrollView.tsx
  components/form-components/Section.tsx
  components/form-components/Switch.tsx
  components/form-components/ToggleCard.tsx
  settings-boundary/AccountInfo.tsx
  settings-boundary/AppearanceSettings.tsx
  settings-boundary/BlockList.tsx
  settings-boundary/CalendarSettings.tsx
  settings-boundary/EventSettings.tsx
  settings-boundary/GeneralSettings.tsx
  settings-boundary/HelpAndSupport.tsx
  settings-boundary/MockData.ts
  settings-boundary/NotificationSettings.tsx
  settings-boundary/PrivacySettings.tsx
  settings-boundary/RootSettings.tsx
Labels: reviews (0)

#391 Arrivals: Remove Buffer Time from `ForegroundEventRegionMonitor`
  arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
  arrival-tracking/region-monitoring/ForegroundRegionMonitor.test.ts
  arrival-tracking/region-monitoring/ForegroundRegionMonitor.ts
  arrival-tracking/region-monitoring/TestHelpers.ts
Labels: reviews (1)

#395 Native Durations Picker
  modules/tif-duration-picker/android/build.gradle
  modules/tif-duration-picker/android/src/main/AndroidManifest.xml
  modules/tif-duration-picker/android/src/main/java/expo/modules/tifdurationpicker/ExpoTiFDurationPickerModule.kt
  modules/tif-duration-picker/android/src/main/java/expo/modules/tifdurationpicker/ExpoTiFDurationPickerView.kt
  modules/tif-duration-picker/expo-module.config.json
  modules/tif-duration-picker/index.ts
  modules/tif-duration-picker/src/DurationPickerView.tsx
  package-lock.json
  package.json
  settings-boundary/EventSettings.tsx
  settings-boundary/EventSettingsDurationPicker.tsx
Labels: reviews (1)
