Repository tifapp/FitnessProject, pull requests merged in 2024-02, with the labels that each got.

#247 Fix Expandable Content Text
  .storybook/components/ContentText/ContextText.stories.tsx
  content-parsing/ExpandableContentText.tsx
Labels: reviews (1)

#246 Push Notifications: Registration + Separate Module
  .storybook/.expo/settings.json
  App.tsx
  api-client/TiFAPI.ts
  babel.config.js
  notifications/RegisterForPushNotifications.test.ts
  notifications/RegisterForPushNotifications.ts
  notifications/UserNotifications.ts
  notifications/index.ts
  root-feature/linkingConfig.test.ts
  root-feature/linkingConfig.ts
  test-helpers/UserNotifications.ts
  tsconfig.json
Labels: reviews (1)

#244 Event Arrivals: Prevent arrivals from being tracked when background location permissions are disabled
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/UpcomingArrivals.test.ts
  event-details/arrival-tracking/UpcomingArrivals.ts
Labels: reviews (1)

#243 Event Details: Join Flow UI
  .storybook/components/ContentText/ContextText.stories.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  content-parsing/ExpandableContentText.tsx
  event-details/JoinEvent.test.tsx
  event-details/JoinEvent.tsx
  event-details/arrival-tracking/region-monitoring/MockRegionMonitors.ts
  event-details/index.ts
Labels: reviews (1)

#245 Event Arrivals: Cleanup + Slim Geofencing
  App.tsx
  event-details/arrival-tracking/Tracker.ts
  event-details/arrival-tracking/geofencing/ExpoGeofencer.ts
  event-details/arrival-tracking/region-monitoring/RegionState.ts
  lib/CallbackCollection.ts
Labels: reviews (0)

#242 Event Details: UseJoinEvent
  .storybook/components/ContentText/ContextText.stories.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  content-parsing/ExpandableContentText.tsx
  event-details/JoinEvent.test.tsx
  event-details/JoinEvent.tsx
  event-details/arrival-tracking/region-monitoring/MockRegionMonitors.ts
  event-details/index.ts
Labels: reviews (1)

#249 Travel Estimates: Update Hook and Types
  event-details/TravelEstimates.test.tsx
  event-details/TravelEstimates.ts
  event-details/travel-estimates/DistanceEvaluator.test.tsx
  event-details/travel-estimates/DistanceEvaluator.ts
  event-details/travel-estimates/index.ts
Labels: reviews (0)

#250 NPM Scripts for doing EAS Builds Locally
  .gitignore
  .storybook/.ondevice/storybook.requires.ts
  package.json
Labels: reviews (0)

#253 Travel Estimates: Native Setup + Code
  .storybook/components/EventDetails/EventDetails.stories.tsx
  event-details/TravelEstimates.ts
  ios/FitnessApp.xcodeproj/project.pbxproj
  ios/FitnessApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Podfile
  ios/Podfile.lock
  lib/utils/RequireOptionalNativeModule.ts
  modules/tif-haptics/src/TifHapticsModule.ts
  modules/tif-travel-estimates/expo-module.config.json
  modules/tif-travel-estimates/index.ts
  modules/tif-travel-estimates/ios/ExpoTiFTravelEstimates.podspec
  modules/tif-travel-estimates/ios/ExpoTiFTravelEstimatesModule.swift
  modules/tif-travel-estimates/src/ExpoTiFTravelEstimatesModule.ts
  native-code/iOS/TiFTravelEstimates/.gitignore
  native-code/iOS/TiFTravelEstimates/.swiftpm/xcode/package.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  native-code/iOS/TiFTravelEstimates/Package.swift
  native-code/iOS/TiFTravelEstimates/Sources/TiFTravelEstimates/CancellableCompletionRequest.swift
  native-code/iOS/TiFTravelEstimates/Sources/TiFTravelEstimates/ExpoObject.swift
  native-code/iOS/TiFTravelEstimates/Sources/TiFTravelEstimates/LocationCoordinate2D.swift
  native-code/iOS/TiFTravelEstimates/Sources/TiFTravelEstimates/MKDirections+Extensions.swift
  native-code/iOS/TiFTravelEstimates/Sources/TiFTravelEstimates/TravelEstimates.swift
  native-code/iOS/TiFTravelEstimates/Sources/TiFTravelEstimates/TravelEstimatesActor.swift
  native-code/iOS/TiFTravelEstimates/Tests/TiFTravelEstimatesTests/CancellableCompletionRequestTests.swift
  native-code/iOS/TiFTravelEstimates/Tests/TiFTravelEstimatesTests/LocationCoordinate2DTests.swift
  native-code/iOS/TiFTravelEstimates/Tests/TiFTravelEstimatesTests/MapKitTravelEstimatesTests.swift
  native-code/iOS/TiFTravelEstimates/Tests/TiFTravelEstimatesTests/TravelEstimatesTests.swift
  native-code/iOS/TiFTravelEstimates/Tests/TiFTravelEstimatesTests/TravelEstimatorActorTests.swift
  native-code/iOS/TiFTravelEstimates/TiFTravelEstimates.podspec
  shared-models/TravelEstimates.ts
Labels: reviews (2)

#252 Add AttendeesList UI
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/AttendeesList/AttendeesList.stories.tsx
  .storybook/package-lock.json
  event-details/attendees-list/AttendeesList.test.tsx
  event-details/attendees-list/AttendeesList.tsx
  package-lock.json
  package.json
  shared-models/Event.ts
Labels: reviews (4)

#256 Add leaveEvent function to tifAPI
  api-client/TiFAPI.ts
Labels: reviews (2)

#255 Travel Estimates: UI
  .storybook/.expo/settings.json
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/ContentText/ContextText.stories.tsx
  .storybook/components/EventDetails/EventDetails.stories.tsx
  .vscode/settings.json
  components/AvatarMapMarker.tsx
  components/common/Icons.tsx
  event-details/TravelEstimates.test.tsx
  event-details/TravelEstimates.ts
  event-details/TravelEstimates.tsx
  lib/utils/DistanceFormatting.ts
  location/search/SearchResultView.tsx
  screens/ExploreEvents/MapMarker.tsx
  shared-models/Location.ts
  shared-models/TravelEstimates.ts
Labels: reviews (1)

#234 Event Details: Loading UI
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/EventDetails/EventDetails.stories.tsx
  event-details/Details.test.tsx
  event-details/Details.tsx
  event-details/EventDetailsLoading.tsx
  ios/Podfile.lock
  lib/utils/Array.ts
  lib/utils/UseConst.ts
  lib/utils/UseInterval.ts
  package-lock.json
  package.json
Labels: reviews (0)

#259 SQLite Migration: Recents Storage
  lib/SQLite.ts
  lib/utils/Array.ts
  lib/utils/DeepNullable.ts
  location/MockData.ts
  location/search/MockData.ts
  location/search/Models.ts
  location/search/RecentsStorage.test.ts
  location/search/RecentsStorage.ts
  location/search/SearchClient.test.ts
  location/search/SearchClient.ts
  location/search/SearchResultsList.tsx
  shared-models/Location.ts
  test-helpers/SQLite.ts
Labels: reviews (1)

#260 SQLite Migration: Logging
  lib/Filesystem.ts
  lib/Logging.test.ts
  lib/Logging.ts
  lib/SQLite.ts
  test-helpers/Filesystem.ts
  test-helpers/SQLite.ts
Labels: reviews (1)

#257 Upgrade Prettier
  .eslintrc.json
  .prettierrc
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/main.js
  .storybook/.ondevice/preview.js
  .storybook/components/EventDetails/EventDetails.stories.tsx
  .storybook/components/RegionMonitoring/RegionMonitoring.stories.tsx
  .vscode/settings.json
  STYLEGUIDE.md
  __mocks__/@react-native-async-storage/async-storage.js
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  android/app/build.gradle
  android/gradle.properties
  androidtimerfix.js
  api-client/TiFAPI.ts
  components/ProfileImageAndName.tsx
  components/ProfileImagePicker.tsx
  components/common/Icons.tsx
  event-details/Details.test.tsx
  event-details/Details.tsx
  event-details/EventDetailsLoading.tsx
  event-details/TravelEstimates.test.tsx
  event-details/TravelEstimates.tsx
  event-details/arrival-tracking/Refresh.ts
  event-details/arrival-tracking/UpcomingArrivals.ts
  index.d.ts
  ios/Podfile.lock
  lib/utils/Array.ts
  lib/utils/UseConst.ts
  lib/utils/UseInterval.ts
  notifications/UserNotifications.ts
  package-lock.json
  package.json
  test-helpers/Promise.ts
Labels: reviews (2)

#258 SQLite Migration: Introduction + Upcoming Event Arrivals
  .vscode/settings.json
  content-parsing/Linkify.ts
  event-details/Event.test.ts
  event-details/arrival-tracking/Refresh.test.ts
  event-details/arrival-tracking/Refresh.ts
  event-details/arrival-tracking/Tracker.test.ts
  event-details/arrival-tracking/UpcomingArrivals.test.ts
  event-details/arrival-tracking/UpcomingArrivals.ts
  event-details/arrival-tracking/region-monitoring/EventArrivalsTrackerRegionMonitor.test.ts
  jest.config.js
  jest/setupSQLite.js
  lib/Filesystem.ts
  lib/InternalMetrics.test.ts
  lib/InternalMetrics.ts
  lib/Logging.test.ts
  lib/Logging.ts
  lib/SQLite.ts
  lib/Sqlite.test.ts
  lib/utils/Array.ts
  lib/utils/DeepNullable.ts
  lib/utils/Object.ts
  location/MockData.ts
  location/search/MockData.ts
  location/search/Models.ts
  location/search/RecentsStorage.test.ts
  location/search/RecentsStorage.ts
  location/search/SearchClient.test.ts
  location/search/SearchClient.ts
  location/search/SearchResultsList.tsx
  package-lock.json
  package.json
  shared-models/Location.ts
  test-helpers/Filesystem.ts
  test-helpers/SQLite.ts
Labels: reviews (0)

#263 SQLite Migration: Remove AsyncStorage
  __mocks__/@react-native-async-storage/async-storage.js
  lib/utils/AsyncStorage.ts
  lib/utils/AsyncStorageUtils.test.ts
  lib/utils/Jotai.ts
  package-lock.json
  package.json
  test-helpers/AsyncStorage.ts
Labels: reviews (2)
