Repository tifapp/FitnessProject, pull requests merged in 2025-03, with the labels that each got.

#471 Location Search Results Fix
  .storybook/.ondevice/Storybook.tsx
  .storybook/.ondevice/storybook.requires.ts
  .storybook/components/RudeusEditor/Register.tsx
  AppEntry.js
  auth-boundary/CognitoHelpers.ts
  event/Menu.test.tsx
  location-search-boundary/Search.tsx
  location-search-boundary/SearchClient.ts
Labels: reviews (2)

#472 Full Screen Map Detail Fix
  components/form-components/Label.tsx
  components/form-components/NamedIconRow.tsx
  event-details-boundary/TravelEstimates.tsx
Labels: reviews (1)

#469 Switch out another PrimaryButton with FormSubmissionPrimaryButton
  .storybook/components/RudeusEditor/PatternEditor.tsx
  .storybook/components/RudeusEditor/Register.tsx
  auth-boundary/AuthLayout.tsx
  components/Buttons.tsx
  edit-event-boundary/Submit.tsx
Labels: reviews (0)

#473 Move current location of event on Edit Event screen
  .storybook/components/EditEvent/PragmaQuote.stories.tsx
  components/MapSnippetView.tsx
  core-root/navigation/EditEvent.tsx
  edit-event-boundary/EditEvent.tsx
  edit-event-boundary/Location.tsx
  event-details-boundary/TravelEstimates.tsx
Labels: reviews (0)

#474 Simple Profile Screen Layout Adjustment
  components/Avatar.tsx
  components/BottomSheet.tsx
  components/Text.tsx
  user-profile-boundary/UserProfile.tsx
Labels: reviews (1)

#475 Add FullScreenOverlay
  App.tsx
  components/BottomSheet.tsx
Labels: reviews (1)

#478 Fix Explore Refetch on Navigate (iOS)
  explore-events-boundary/ExploreEvents.tsx
  location/UserLocation.tsx
Labels: reviews (1)

#477 Fix Modal Presentation
  .storybook/.ondevice/storybook.requires.ts
  components/BottomSheet.tsx
  components/Navigation.tsx
  core-root/HomeLiveEvents.tsx
  explore-events-boundary/BottomSheet.tsx
  explore-events-boundary/ExploreEvents.tsx
  location/UserLocation.tsx
Labels: reviews (2)

#479 Basic Map View Type Picker
  components/Avatar.tsx
  components/MapSnippetView.tsx
  components/form-components/MapTypePicker.tsx
  components/form-components/MenuPicker.tsx
  explore-events-boundary/ExploreEvents.tsx
  explore-events-boundary/Map.tsx
Labels: reviews (1)

#480 Use Coordinate Instead of Placemark
  .storybook/.ondevice/storybook.requires.ts
  edit-event-boundary/FormAtoms.test.ts
  edit-event-boundary/FormAtoms.ts
  edit-event-boundary/Submit.test.tsx
Labels: reviews (0)

#481 Global Query Cache Logging
  .storybook/components/TiFPreview/TiFPreview.stories.tsx
  lib/ReactQuery.test.tsx
  lib/ReactQuery.tsx
  location-search-boundary/Search.tsx
Labels: reviews (1)
